import Image from "next/image";
import type {Metadata} from "next";
import {ContentPage} from "../content-page";
export const metadata:Metadata={title:"Sandra Pavić Drašković",description:"Magistra farmacije, fitoaromaterapeutkinja i edukatorica iza obrta Natura Sanat.",alternates:{canonical:"/sandra"}};
export default function Page(){return <ContentPage eyebrow="Sandra Pavić Drašković" title="Znanje povezano s osobnim iskustvom." intro="Magistra sam farmacije, fitoaromaterapeutkinja, specijalistica regenerativne detoksikacije i edukatorica. Kroz Natura Sanat radim s ljudima koji žele bolje razumjeti prehranu, dodatke i svoje svakodnevne navike.">
<figure className="portrait-inline"><Image src="/images/sandra/sandra-cafe-green.jpg" alt="Sandra Pavić Drašković za stolom sa zelenim napitkom" width={1358} height={1474} sizes="(max-width:900px) 100vw, 55vw"/></figure><h2>Zašto radim ovaj posao</h2><p>Godine 2017. dijagnosticiran mi je rak debelog crijeva s metastazama u jetri. Bolest je promijenila moj život i način na koji slušam ljude. Dobro poznajem osjećaj kad imaš mnogo pitanja, a teško je odvojiti korisnu informaciju od obećanja.</p><p>Moja priča je osobno iskustvo, ne dokaz učinkovitosti određene prehrane ili pripravka. Ne koristim je kao jamstvo tuđeg oporavka. Prehrambena podrška ne zamjenjuje onkološko liječenje.</p>
<h2>Natura Sanat</h2><p>Obrt sam osnovala 2021. godine. Danas održavam individualna savjetovanja, predavanja i radionice te pripremam edukativne vodiče s receptima.</p><p>Rad nije ograničen na jednu dijagnozu. Podrška se prilagođava osobama koje žele djelovati preventivno, urediti prehranu i tjelesnu težinu, imati više energije, podržati sportske ciljeve, lakše proći menopauzu ili prehranu i navike uskladiti s trenutačnim zdravstvenim stanjem.</p><p>U radu me zanimaju navike koje osoba može održati: kako kupuje, priprema obroke, što već uzima i gdje zapinje. Smjernice trebaju biti razumljive i izvedive.</p>
<h2>Suradnje i edukacije</h2><p>U suradnji s udrugom Budi dobro i Institutom za gastroenterološke tumore sudjelujem u radionicama prehrane za onkološke bolesnike. Za organizacije pripremam predavanja prema potrebama publike.</p>
<h2>Granice mog rada</h2><p>Ne postavljam dijagnoze, ne propisujem liječenje i ne mijenjam terapiju. Kada pitanje prelazi opseg savjetovanja, važno je uključiti liječnika ili odgovarajućeg zdravstvenog stručnjaka.</p><a className="arrow-link" href="/savjetovanje">Kako izgleda savjetovanje →</a></ContentPage>}
