import Image from "next/image";
import {Footer,Header} from "../site-components";

export default function Page(){return <><Header/><main>
<section className="sandra-hero"><div><p className="kicker">O Sandri</p><h1>Stručno znanje koje ostaje razumljivo.</h1><p>Sandra Pavić Drašković je magistra farmacije, fitoaromaterapeutkinja i edukatorica.</p></div><figure><Image src="/images/sandra/sandra-green-glass.jpg" alt="Sandra Pavić Drašković u svijetlom interijeru sa zelenim napitkom" fill priority sizes="(max-width: 900px) 100vw, 46vw"/></figure></section>
<section className="detail-grid wrap"><div><p className="kicker">Pristup radu</p><h2>Osoba i njezin kontekst dolaze prije preporuke.</h2></div><div><p>Kroz individualne konzultacije, predavanja, radionice i pisane materijale Sandra približava stručne teme ljudima koji žele donositi informiranije zdravstvene odluke.</p><p>Njezina edukacija ne zamjenjuje liječnički pregled, dijagnozu ni propisanu terapiju.</p></div></section>
<section className="photo-strip" aria-label="Sandra u radu i svakodnevnom okruženju"><figure><Image src="/images/sandra/sandra-melon.jpeg" alt="Sandra s posudom svježeg voća" fill sizes="33vw"/></figure><figure><Image src="/images/sandra/sandra-tea.jpeg" alt="Sandra uz šalicu čaja" fill sizes="33vw"/></figure><figure><Image src="/images/sandra/sandra-cafe-green.jpg" alt="Sandra u razgovoru za stolom" fill sizes="33vw"/></figure></section>
<section className="collab wrap"><div><p className="kicker">Edukacije i suradnje</p><h2>Institut IGET i Udruga Budi dobro.</h2></div><div><p>Na webu ih navodimo kao organizacije s kojima Sandra surađuje, bez logotipa i bez naziva službeni partner dok se ne potvrdi točan oblik suradnje.</p><p className="fine">TODO_CONFIRM_INSTITUTIONAL_COLLABORATION · TODO_CONFIRM_LOGO_USAGE_PERMISSION</p></div></section>
</main><Footer/></>}
