import Image from "next/image";
import {Footer,Header} from "../site-components";

const includes=["pregled zdravstvenog upitnika","razgovor o prehrani i životnim navikama","pregled popisa lijekova, dodataka prehrani i biljnih pripravaka","edukaciju o važnim temama i mogućim interakcijama","pisane individualizirane edukativne smjernice","prijedlog daljnjih koraka"];

export default function Page(){return <><Header/><main>
<section className="page-hero yellow"><div><p className="kicker">Individualne konzultacije</p><h1>Razgovor o navikama, dodacima i svakodnevnim odlukama.</h1><p className="lede">Online putem Zooma ili uživo prema dogovoru.</p></div><aside><span>Trajanje</span><strong>90 minuta</strong><span>Cijena</span><strong>200 €</strong></aside></section>
<section className="detail-grid wrap"><div><p className="kicker">Kome su namijenjene</p><h2>Za osobe koje žele bolje razumjeti svoje navike.</h2></div><div><p>Konzultacije su namijenjene osobama koje žele jasnije sagledati prehranu, životni stil, dodatke prehrani i odluke koje svakodnevno donose.</p><p>Prije susreta Sandra pregledava upitnik i podatke koje klijent dobrovoljno dostavi. Razgovaraju o prehrani, terapiji, dostupnim nalazima, simptomima, snu, stresu i životnom ritmu.</p><p>Nakon susreta klijent dobiva pisane edukativne smjernice i prijedlog koraka koje može postupno uključiti u svakodnevni život.</p></div></section>
<section className="split stone"><figure><Image src="/images/sandra/sandra-consultation-v1.webp" alt="Sandra Drašković u kuhinji drži čašu zelenog napitka" fill sizes="(max-width: 900px) 100vw, 50vw"/></figure><div><p className="kicker">Što uključuje</p><h2>Priprema, razgovor i pisane smjernice.</h2><ul className="lined-list">{includes.map(x=><li key={x}>{x}</li>)}</ul></div></section>
<section className="privacy wrap"><div><p className="kicker">Zdravstveni podaci</p><h2>Upit nije zdravstveni upitnik.</h2></div><div><p>Na webu se ne prikupljaju nalazi, dijagnoze, terapija ni drugi zdravstveni podaci. Nakon prvog kontakta Sandra šalje upute za zaseban siguran proces.</p><p className="notice">Konzultacije ne uključuju postavljanje dijagnoze, liječenje bolesti niti promjenu terapije koju je propisao liječnik.</p><a className="button" href="/kontakt?tema=konzultacije">Pošalji upit za konzultacije</a></div></section>
</main><Footer/></>}
