import Image from "next/image";
import {Footer,Header} from "../site-components";

const includes=["pregled zdravstvenog upitnika","razgovor o prehrani i životnim navikama","pregled popisa lijekova, dodataka prehrani i biljnih pripravaka","edukaciju o važnim temama i mogućim interakcijama","pisane individualizirane edukativne smjernice","prijedlog daljnjih koraka"];

export default function Page(){return <><Header/><main>
<section className="page-hero yellow"><div><p className="kicker">Individualne konzultacije</p><h1>Kad znaš puno, ali više ne znaš što je važno.</h1><p className="lede">Devedeset minuta da usporimo, povežemo informacije i pronađemo mjesto od kojeg ima smisla krenuti. Online putem Zooma ili uživo prema dogovoru.</p></div><aside><span>Trajanje</span><strong>90 minuta</strong><span>Cijena</span><strong>200 €</strong></aside></section>
<section className="detail-grid wrap"><div><p className="kicker">Je li ovo za mene?</p><h2>Možda ti ne treba još savjeta. Možda ti treba red među njima.</h2></div><div><p>Možda već dugo čitaš, slušaš i pokušavaš. Imaš popis dodataka, nekoliko nalaza, terapiju koju uzimaš i navike koje bi navodno trebalo promijeniti. Samo nitko još nije s tobom sve to stavio na isti stol.</p><p>Prije susreta Sandra čita tvoj upitnik i podatke koje odlučiš podijeliti. Na razgovoru prolazite prehranu, lijekove i dodatke, simptome, san, stres i tempo u kojem živiš. Ne traži se savršen dan. Traži se ono što u tvojem danu ima smisla.</p><p>Nakon susreta dobivaš pisane edukativne smjernice. Ne moraš pamtiti svaku rečenicu ni odmah promijeniti sve.</p></div></section>
<section className="split stone"><figure><Image src="/images/sandra/sandra-consultation-v1.webp" alt="Sandra Drašković u kuhinji drži čašu zelenog napitka" fill sizes="(max-width: 900px) 100vw, 50vw"/></figure><div><p className="kicker">Što uključuje</p><h2>Prije razgovora Sandra čita. Tijekom razgovora sluša. Nakon njega piše.</h2><ul className="lined-list">{includes.map(x=><li key={x}>{x}</li>)}</ul></div></section>
<section className="privacy wrap"><div><p className="kicker">Važna granica</p><h2>Ovdje se znanje prevodi. Medicina se ne zamjenjuje.</h2></div><div><p>Prvi upit služi samo dogovoru. Nalazi, dijagnoze i terapija ne šalju se kroz javni obrazac. Ako dogovorite konzultaciju, Sandra će objasniti siguran sljedeći korak.</p><p className="notice">Konzultacije ne uključuju postavljanje dijagnoze, liječenje bolesti niti promjenu terapije koju je propisao liječnik.</p><a className="button" href="/kontakt?tema=konzultacije">Pošalji upit za konzultacije</a></div></section>
</main><Footer/></>}
