"use client";
import {useMemo,useState} from "react";
import Link from "next/link";

const steps=[
 {title:"Smjer projekta",intro:"Najprije definiramo što web treba napraviti za Sandrin posao.",questions:["Što želiš da ti web donese u prvih šest mjeseci?","Koja ti je ponuda sada najvažnija: individualni rad, Health Reset, knjižice ili predavanja?","Od čega bi željela najviše zarađivati za godinu dana?","Koliko novih klijenata ili kupaca realno možeš primiti mjesečno?"]},
 {title:"Ljudi kojima se obraćaš",intro:"Ne trebamo govoriti svima. Trebamo znati kome Sandra najviše može pomoći.",questions:["Tko ti se danas najčešće javlja i zbog čega?","S kim najviše voliš raditi?","Koga više ne želiš privlačiti?","Što je osoba obično već pokušala prije nego što dođe do tebe?","Što je najčešće sprječava da promjenu zadrži?"]},
 {title:"Pozicioniranje",intro:"Tražimo riječi koje zvuče kao Sandra, ne kao generičan wellness brand.",questions:["Prepoznaješ li se u rečenici „Brini o zdravlju prije nego što moraš”?","Koje tri riječi najbolje opisuju tvoj način rada?","Koje tri riječi nikako ne želiš uz svoj brand?","Po čemu se tvoj rad razlikuje od rada nutricionista, liječnika i wellness savjetnika?","Koliko želiš javno govoriti o vlastitom iskustvu bolesti?"]},
 {title:"Usluge",intro:"Svaka ponuda mora imati jasan sadržaj, cijenu i granicu.",questions:["Što klijent točno dobiva kroz Health Review?","Što klijent treba pripremiti prije razgovora i što dobiva nakon njega?","Postoji li Health Reset već ili ga tek razvijamo?","Kako izgleda šest tjedana Health Reseta u praksi?","Koji rezultat smijemo realno obećati, a što ne želiš obećavati?"]},
 {title:"Digitalne knjižice",intro:"Za prodaju trebamo stvarne podatke o svakom PDF proizvodu.",questions:["Koliko digitalnih knjižica trenutno postoji i kako se zovu?","Koju bi knjižicu prvu istaknula i zašto?","Koji problem rješava svaka knjižica i kome je namijenjena?","Koliko stranica imaju, jesu li završene i medicinski pregledane?","Koja je cijena svake knjižice i želiš li paket svih knjižica?","Smijemo li na webu pokazati nekoliko oglednih stranica?","Preko kojeg pravnog subjekta prodaješ i tko izdaje račun?"]},
 {title:"Predavanja",intro:"B2B ponuda treba biti dovoljno konkretna da je HR ili organizator može naručiti.",questions:["Koje četiri teme želiš aktivno nuditi?","Koje si tvrtke, udruge ili događaji smijemo navesti kao reference?","Koliko traje standardno predavanje i što uključuje cijena?","Koja je početna cijena i naplaćuju li se putni troškovi posebno?","Što želiš da organizator napravi nakon što vidi ponudu?"]},
 {title:"Vizual i sadržaj",intro:"Web mora izgledati kao digitalni nastavak Sandre uživo.",questions:["Koji webovi, časopisi ili brandovi izgledaju kao ti?","Kako reagiraš na spoj tamne grafitne, zelene i svijetle zeleno-žute?","Koliko želiš da voće, povrće i biljke budu prisutni u vizualnom identitetu?","Koje boje, stilove i wellness klišeje ne želiš?","Koje profesionalne fotografije već imaš?","Jesi li spremna za novo fotografiranje i vođeno snimanje kratkih videa?"]},
 {title:"Produkcija",intro:"Na kraju zaključavamo opseg, odgovornost i rok.",questions:["Kada želiš lansirati web?","Postoji li događaj ili program prije kojeg web mora biti spreman?","Imaš li domenu, poslovni email i pristup postojećim računima?","Tko donosi konačnu odluku o sadržaju i dizajnu?","Što mora biti u prvoj verziji, a što može čekati?","Koji je budžet za strategiju, web, fotografiranje i prodaju knjižica?","Tko će nakon lansiranja održavati web i unositi novi sadržaj?"]},
];

export default function Upitnik(){
 const [step,setStep]=useState(0);const [answers,setAnswers]=useState<Record<string,string>>({});const [done,setDone]=useState(false);const [copied,setCopied]=useState(false);
 const total=steps.reduce((n,s)=>n+s.questions.length,0);const answered=Object.values(answers).filter(Boolean).length;
 const summary=useMemo(()=>steps.map((s,si)=>[s.title,...s.questions.map((q,qi)=>`${q}\n${answers[`${si}-${qi}`]||"Nije odgovoreno"}`)].join("\n\n")).join("\n\n──────────\n\n"),[answers]);
 const copy=async()=>{await navigator.clipboard.writeText(summary);setCopied(true)};
 if(done)return <main className="wizard wizard-summary"><div className="wizard-top"><Link href="/">Sandra Pavić Drašković</Link><span>Sažetak sastanka</span></div><div className="wizard-result"><p className="kicker">Završeno {answered} od {total}</p><h1>Odgovori za projekt</h1><pre>{summary}</pre><div className="wizard-actions"><button onClick={copy}>{copied?"Kopirano":"Kopiraj sve odgovore"}</button><button className="quiet" onClick={()=>setDone(false)}>Vrati se na pitanja</button></div></div></main>;
 const current=steps[step];
 return <main className="wizard"><div className="wizard-top"><Link href="/">Sandra Pavić Drašković</Link><span>Projektni upitnik</span></div><div className="wizard-progress"><span style={{width:`${((step+1)/steps.length)*100}%`}}/></div><section className="wizard-step"><div className="wizard-step__intro"><p className="kicker">Korak {step+1} od {steps.length}</p><h1>{current.title}</h1><p>{current.intro}</p></div><div className="wizard-fields">{current.questions.map((q,i)=><label key={q}><span>{q}</span><textarea value={answers[`${step}-${i}`]||""} onChange={e=>setAnswers({...answers,[`${step}-${i}`]:e.target.value})} rows={3} placeholder="Sandrin odgovor"/></label>)}</div><div className="wizard-actions"><button className="quiet" disabled={step===0} onClick={()=>setStep(step-1)}>Natrag</button>{step<steps.length-1?<button onClick={()=>setStep(step+1)}>Dalje</button>:<button onClick={()=>setDone(true)}>Prikaži sažetak</button>}</div></section></main>
}
