import {LegalPage} from "../legal-page";

export default function Page(){return <LegalPage title="Priprema, suglasnosti i dokumenti" intro="Prije savjetovanja treba biti jasno što usluga uključuje, treba li uopće dokumentacija i koje podatke dijeliš. U prvi kontakt nikada ne šalji zdravstvene podatke.">
<section><h2>Kada je medicinska dokumentacija potrebna?</h2><p>Kratak odgovor: <strong>samo za dio individualnog rada i samo kada Sandra nakon uvodnog dogovora potvrdi da je relevantna.</strong> Za grupne edukacije, snimke i digitalne vodiče nije potrebna.</p><div className="table-scroll"><table className="service-matrix"><thead><tr><th>Usluga ili korak</th><th>Dokumentacija</th><th>Što se šalje</th></tr></thead><tbody>
<tr><th>Prvi kontakt</th><td><strong>Ne</strong></td><td>Kontakt i kratka tema upita, bez dijagnoza, nalaza i terapije.</td></tr>
<tr><th>Uvodno savjetovanje</th><td><strong>Ponekad</strong></td><td>Samo relevantni postojeći nalazi ili popis lijekova i dodataka koje Sandra izričito zatraži nakon obavijesti i privole.</td></tr>
<tr><th>Daljnji individualni rad</th><td><strong>Prema procjeni</strong></td><td>Samo podaci nužni za dogovoreni opseg usluge, sigurnim dogovorenim kanalom.</td></tr>
<tr><th>Predavanje ili radionica</th><td><strong>Ne</strong></td><td>Organizacijski podaci; ne prikupljaju se nalazi sudionika.</td></tr>
<tr><th>Snimka, e-knjiga ili vodič</th><td><strong>Ne</strong></td><td>Samo podaci potrebni za narudžbu i dostavu.</td></tr>
<tr><th>Suradnja s tvrtkom ili udrugom</th><td><strong>Ne</strong></td><td>Podaci za ponudu i organizaciju, bez zdravstvenih podataka sudionika.</td></tr>
</tbody></table></div></section>
<section><h2>Siguran redoslijed</h2><ol className="process-list"><li><strong>Upit bez osjetljivih podataka.</strong> Pošalji samo kontakt i temu.</li><li><strong>Ponuda i opseg.</strong> Dobivaš opis usluge, cijenu i granice rada.</li><li><strong>Obavijest i odvojena privola.</strong> Prije zdravstvenih podataka mora biti jasno zašto se traže, tko ih prima i koliko se čuvaju.</li><li><strong>Izričit zahtjev za dokumentacijom.</strong> Šalje se samo ono što je dogovoreno i samo dogovorenim sigurnim kanalom.</li><li><strong>Usluga i daljnje upute.</strong> Nova dokumentacija ili pretrage ne traže se automatski.</li></ol></section>
<section><h2>Priprema za razgovor</h2><p>Za početak zapiši kako izgleda prehrana tijekom dva uobičajena dana. Cilj nije uljepšati jelovnik, nego opisati obroke i pića kakvi stvarno jesu.</p><p>Ne radi nove laboratorijske pretrage niti kućne testove samo zato što rezerviraš savjetovanje. Ako su podaci potrebni, Sandra će objasniti razlog i uputiti te da medicinske postupke dogovoriš s liječnikom.</p></section>
<section><h2>Prihvat opsega savjetovanja</h2><p>Prije početka usluge korisnik dobiva dokument koji opisuje edukativni opseg rada, cijenu, pisane materijale i granice usluge. Prihvat potvrđuje zasebno, u dogovorenom postupku.</p><p>Savjetovanje nije dijagnostika ni liječenje i ne mijenja liječničke preporuke. Korisnik se ne odriče zakonskih prava ni prava na prigovor.</p></section>
<section><h2>Privola za zdravstvene podatke</h2><p>Upitnik, podaci o terapiji i relevantna dokumentacija obrađuju se samo u zasebno dogovorenom postupku. Prije dostave korisnik treba dobiti informacije o svrsi, pravnoj osnovi, primateljima, roku čuvanja, sigurnosti i svojim pravima.</p><p>Privola, kada je odgovarajuća pravna osnova, traži se izričito i odvojeno od newslettera ili marketinških poruka. Može se povući putem <a href="/kontakt">kontaktnog obrasca</a>. Povlačenje ne utječe na zakonitost prethodne obrade.</p></section>
<section><h2>Kada uslugu plaća druga osoba</h2><p>Osoba koja plaća ne daje privolu za zdravstvene podatke druge punoljetne osobe. Korisnik usluge treba sam dobiti obavijesti i potvrditi potrebne prihvate prije dostave dokumentacije. Dokumenti trebaju razlikovati izravno savjetovanje korisnika od edukacije osobe koja mu pruža skrb.</p></section>
<section><h2>Zdravstveni upitnik i pisane smjernice</h2><p>Suglasnost i upitnik nisu javno dostupni. Nakon potvrđene kupnje Sandra klijentu šalje osobnu privatnu poveznicu za online ispunjavanje i elektronički potpis.</p><p>Ispunjeni upitnici nisu javni dokumenti. Individualne pisane smjernice dobiva samo korisnik kojem su namijenjene.</p></section></LegalPage>}
