import type {Metadata} from "next";
import Image from "next/image";
import {Footer,Header} from "../site-components";
import {PressCopy} from "./press-copy";

export const metadata:Metadata={
  title:"Za medije i organizatore",
  description:"Biografije, opis projekta, fotografije i teme za razgovore, gostovanja i edukacije Sandre Pavić Drašković i Natura Sanat.",
};

const projectOneLine="Natura Sanat je savjetodavni i edukativni projekt Sandre Pavić Drašković, mag. pharm., posvećen prehrani, fitoaromaterapiji, suplementaciji i održivim životnim navikama.";
const projectShort="Natura Sanat okuplja individualna savjetovanja, edukativne programe, predavanja, radionice i digitalne vodiče Sandre Pavić Drašković, mag. pharm. U radu povezuje farmaceutsko znanje, praktično razumijevanje prehrane i osobno iskustvo ozbiljne bolesti. Sadržaj je edukativan i komplementaran liječničkoj skrbi; ne zamjenjuje dijagnozu, liječenje ni propisanu terapiju.";
const projectLong="Natura Sanat je savjetodavni i edukativni projekt koji je Sandra Pavić Drašković, mag. pharm., pokrenula kako bi ljudima pomogla jasnije razumjeti prehranu, dodatke prehrani, fitoaromaterapiju i svakodnevne životne navike. Projekt obuhvaća individualna savjetovanja, strukturirane programe, predavanja i praktične radionice za građane, udruge, tvrtke i organizacije te digitalne vodiče s receptima. Sandra u radu povezuje farmaceutsko obrazovanje, iskustvo edukatorice i vlastiti put nakon onkološke bolesti. Naglasak stavlja na razumljive informacije i promjene koje se mogu uklopiti u stvaran život. Natura Sanat ne postavlja dijagnoze, ne propisuje liječenje i ne mijenja liječničku terapiju. Savjetovanja i edukativni sadržaji zamišljeni su kao podrška odgovornom donošenju odluka i, kada je potrebno, suradnji s nadležnim zdravstvenim stručnjacima.";

const bioTiny="Sandra Pavić Drašković, mag. pharm., fitoaromaterapeutkinja je i edukatorica te osnivačica Natura Sanat, projekta koji povezuje individualno savjetovanje, edukacije i praktične vodiče o prehrani i životnim navikama.";
const bioShort="Sandra Pavić Drašković magistrica je farmacije, fitoaromaterapeutkinja i edukatorica. Kroz Natura Sanat održava individualna savjetovanja, predavanja i radionice te izrađuje edukativne vodiče s receptima. U radu povezuje stručno znanje, praktičnu primjenu i osobno iskustvo onkološke bolesti, uz jasno poštovanje granica savjetovanja i liječničke terapije.";
const bioLong="Sandra Pavić Drašković, mag. pharm., magistrica je farmacije, fitoaromaterapeutkinja i edukatorica te osnivačica Natura Sanat. Nakon vlastitog iskustva onkološke bolesti dodatno se posvetila razumijevanju prehrane, navika i podrške koja ljudima može pomoći u svakodnevnom životu. Danas održava individualna savjetovanja, edukativne programe, predavanja i praktične radionice te priprema digitalne vodiče s receptima. Surađuje s udrugama i inicijativama koje pružaju edukativnu podršku osobama suočenima s ozbiljnom bolešću. U svojem radu naglašava važnost razumljivih informacija, realnih koraka i odgovornog odnosa prema suplementima i fitoaromaterapijskim pripravcima. Osobno iskustvo predstavlja kao vlastitu priču, a ne kao jamstvo ishoda za druge osobe. Natura Sanat ne zamjenjuje liječnički pregled, dijagnozu, liječenje ni propisanu terapiju.";

const topics=[
  ["Prehrana koja stane u stvaran život","Kako prijeći od općih preporuka prema obrocima i navikama koje osoba može dugoročno održati."],
  ["Dodaci prehrani bez nagađanja","Kako razmišljati o suplementima, deklaracijama, terapiji i pitanjima koja vrijedi postaviti stručnjaku."],
  ["Osobna priča, odgovorna komunikacija","Kako govoriti o iskustvu ozbiljne bolesti bez univerzalnih obećanja i pojednostavljenih rješenja."],
  ["Edukacija u zajednici","Predavanja i praktične radionice za udruge, tvrtke i organizacije prilagođene publici i konkretnom formatu."],
] as const;

export default function Page(){return <><Header/><main>
  <section className="press-hero"><div className="wrap press-hero-grid"><div><p className="kicker">Za medije i organizatore</p><h1>Priča, stručni okvir i materijali. Na jednom mjestu.</h1><p className="lede">Tekstovi, biografije i trenutačni vizuali za pripremu članka, razgovora, najave ili edukativnog gostovanja sa Sandrom Pavić Drašković.</p><div className="actions"><a className="button" href="#tekstovi">Tekstovi za kopiranje</a><a className="arrow-link" href="#materijali">Fotografije i logo</a></div></div><figure><Image src="/images/sandra/sandra-portrait-green-v2.jpg" alt="Sandra Pavić Drašković" fill priority sizes="(max-width:900px) 100vw, 42vw"/></figure></div></section>

  <nav className="press-index wrap" aria-label="Sadržaj stranice"><a href="#tekstovi"><span>01</span>Tekstovi</a><a href="#biografije"><span>02</span>Biografije</a><a href="#materijali"><span>03</span>Media kit</a><a href="#identitet"><span>04</span>Fontovi i boje</a><a href="#teme"><span>05</span>Teme i gostovanja</a><a href="#kontakt"><span>06</span>Kontakt</a></nav>

  <section className="press-section wrap" id="tekstovi"><header><p className="kicker">Opis projekta</p><h2>Spremno za copy/paste.</h2><p>Neutralne tekstove možete preuzeti, skratiti i urednički prilagoditi uz zadržavanje njihova smisla.</p></header><div className="press-copy-list"><PressCopy label="Natura Sanat u jednoj rečenici" text={projectOneLine}/><PressCopy label="Kratki opis" text={projectShort}/><PressCopy label="Dulji opis" text={projectLong}/></div></section>

  <section className="press-section press-bios" id="biografije"><div className="wrap"><header><p className="kicker">O Sandri</p><h2>Biografije u tri duljine.</h2></header><div className="press-copy-list"><PressCopy label="Vrlo kratka biografija" text={bioTiny}/><PressCopy label="Kratka biografija" text={bioShort}/><PressCopy label="Duža biografija" text={bioLong}/></div></div></section>

  <section className="press-section wrap" id="materijali"><header><p className="kicker">Materijali za preuzimanje</p><h2>Natura Sanat media kit.</h2><p>Preuzmite objedinjeni paket s biografijama, opisom projekta, trenutačnim logom, odabranim fotografijama, fontovima i osnovnim pravilima vizualnog identiteta.</p><a className="button press-download-button" href="/media-kit/Natura-Sanat-media-kit.zip" download>Preuzmite cijeli media kit ↓</a></header><div className="press-assets"><article><figure><Image src="/images/sandra/sandra-portrait-green-v2.jpg" alt="Portret Sandre Pavić Drašković" fill sizes="(max-width:900px) 100vw, 32vw"/></figure><div><span>Portret</span><h3>Sandra Pavić Drašković</h3><p>Za objavu prije uporabe zatražite potvrdu potpisa fotografije.</p><a className="arrow-link" href="/images/sandra/sandra-portrait-green-v2.jpg" download>Preuzmi fotografiju ↓</a></div></article><article><figure className="press-logo-preview"><Image src="/natura-sanat-logo-green.png" alt="Trenutačni Natura Sanat logo" width={420} height={420}/></figure><div><span>Trenutačna verzija</span><h3>Natura Sanat logo</h3><p>Logo će se kasnije zamijeniti konačnim znakom bez promjene strukture stranice.</p><a className="arrow-link" href="/natura-sanat-logo-green.png" download>Preuzmi PNG ↓</a></div></article><article><figure><Image src="/images/sandra/sandra-speaking-nutricentar-v2.jpg" alt="Sandra Pavić Drašković tijekom predavanja" fill sizes="(max-width:900px) 100vw, 32vw"/></figure><div><span>Edukacija</span><h3>Sandra tijekom predavanja</h3><p>Fotografija za najave predavanja i radionica.</p><a className="arrow-link" href="/images/sandra/sandra-speaking-nutricentar-v2.jpg" download>Preuzmi fotografiju ↓</a></div></article></div><aside className="press-usage"><strong>Uporaba materijala</strong><p>Materijale koristite za uredničke priloge i najave o Sandri i Natura Sanat. Ne mijenjajte boje ni proporcije logotipa. Fotografije i gostovanja objavite uz dogovoreni potpis te nakon potvrde teme i termina.</p></aside></section>

  <section className="press-section press-identity" id="identitet"><div className="wrap"><header><p className="kicker">Vizualni identitet</p><h2>Fontovi koje Sandra može koristiti svugdje.</h2><p>Brend koristi P22 Mackinac Book za elegantne, uredničke naslove i Manrope za jasan tekst. Mackinac je licencirani font, dok je Manrope dostupan prema otvorenoj licenci.</p></header><div className="press-type-grid"><article className="press-type-serif"><span>Naslovi · P22 Mackinac Book</span><p>Znanje koje budi životnu energiju i vitalnost.</p><small>Naslovnice, glavni naslovi, citati i kratke istaknute poruke.</small></article><article className="press-type-sans"><span>Tekst · Manrope</span><p>Stručno znanje, osobno razumijevanje i jasni koraci za svakodnevni život.</p><small>Odlomci, podnaslovi, cijene, gumbi, objave i prezentacije.</small></article></div><div className="press-palette" aria-label="Boje vizualnog identiteta"><div><i style={{background:"#1D4C3D"}}/><span>Tamnozelena<br/><strong>#1D4C3D</strong></span></div><div><i style={{background:"#F3F1E8"}}/><span>Krem papir<br/><strong>#F3F1E8</strong></span></div><div><i style={{background:"#252723"}}/><span>Tamni tekst<br/><strong>#252723</strong></span></div><div><i style={{background:"#DFF44D"}}/><span>Akcent<br/><strong>#DFF44D</strong></span></div></div><div className="actions"><a className="button" href="/media-kit/Natura-Sanat-fontovi.zip" download>Preuzmite Manrope i licencu ↓</a><a className="arrow-link" href="/media-kit/Natura-Sanat-tipografija-i-boje.txt" download>Preuzmite kratke smjernice</a></div></div></section>

  <section className="press-section press-topics" id="teme"><div className="wrap"><header><p className="kicker">Intervju · podcast · predavanje</p><h2>Teme o kojima Sandra može govoriti.</h2></header><div className="press-topic-grid">{topics.map(([title,description],index)=><article key={title}><span>0{index+1}</span><h3>{title}</h3><p>{description}</p></article>)}</div><div className="press-organizer"><div><p className="kicker">Za urednike i organizatore</p><h3>Trebate najavu, izjavu ili edukativno gostovanje?</h3><p>U poruci navedite medij ili organizaciju, temu, format, publiku i željeni termin. Opseg, pripremu i uvjete suradnje dogovorit ćemo pojedinačno.</p></div><div><a className="button" href="mailto:info@naturasanat.hr?subject=Upit%20za%20medije%20ili%20gostovanje">Pošaljite upit</a><a className="arrow-link" href="/mediji">Pogledajte dosadašnje objave</a></div></div></div></section>

  <section className="press-contact" id="kontakt"><div className="wrap"><p className="kicker">Kontakt</p><h2>Pripremate razgovor, članak ili događanje?</h2><p>Napišite što pripremate, za koju publiku i do kada trebate odgovor ili materijale.</p><a href="mailto:info@naturasanat.hr">info@naturasanat.hr <span aria-hidden>↗</span></a></div></section>
</main><Footer/></>}
