import type {Metadata} from "next";
import {LegalPage} from "../legal-page";
export const metadata:Metadata={title:"Uvjeti usluga i plaćanja",description:"Uvjeti ugovaranja, plaćanja, promjene termina i korištenja digitalnih vodiča Natura Sanat.",alternates:{canonical:"/uvjeti-kupnje"}};
export default function Page(){return <LegalPage title="Uvjeti usluga i plaćanja" intro="Ovi uvjeti objašnjavaju kako se ugovaraju i plaćaju Natura Sanat savjetovanja, programi i digitalni vodiči. Zakonska prava potrošača ostaju u cijelosti očuvana.">
<h2>Pružatelj usluge</h2><p>Natura Sanat, obrt za nutricionističko i fitoaromaterapijsko savjetovanje, vl. Sandra Pavić Drašković, Zelenjak 38, 10000 Zagreb. OIB: 77515854476. MBO: 98353055.</p><p>Za kontakt koristite <a href="/kontakt">kontaktni obrazac</a>. Pisani prigovor može se poslati i na navedenu poštansku adresu.</p>
<h2>Ugovaranje i potvrda termina</h2><p>Slanje upita nije kupnja ni rezervacija. Nakon provjere odgovara li usluga vašoj potrebi dogovaraju se opseg, cijena, način održavanja i termin. Zatim dobivate pisanu ponudu i podatke za plaćanje.</p><p><strong>Termin je potvrđen tek kada je evidentirana puna uplata ili prva dogovorena rata.</strong> Ako uplata ne bude zaprimljena u roku navedenom u ponudi, privremeno zadržani termin može se osloboditi.</p>
<h2>Način plaćanja</h2><p>Usluge do 200 € plaćaju se u cijelosti unaprijed. Program od 400 € može se platiti u cijelosti ili u 2 rate po 200 €, program od 600 € u cijelosti ili u 3 rate po 200 €, a program Put zdravlja od 950 € u cijelosti ili u 5 rata po 190 €. Svaka rata dospijeva prije pripadajućeg termina.</p><p>Uvodno savjetovanje od 150 € ugovara se i plaća zasebno. Nakon procjene možete dobiti prijedlog daljnjeg programa, ali niste ga obvezni prihvatiti.</p>
<h2>Otkazivanje ili promjena termina od strane klijenta</h2><p>Ako promjenu ili otkazivanje javite najmanje 48 sati prije dogovorenog termina, možete jednom odabrati novi raspoloživi termin ili zatražiti povrat iznosa plaćenog za neizvršenu uslugu.</p><p>Kod otkazivanja manje od 48 sati prije termina ili nedolaska uplaćeni iznos se u pravilu ne vraća jer su vrijeme i priprema bili rezervirani za vas. U opravdanim i dokumentiranim iznimnim okolnostima može se ponuditi novi termin.</p>
<h2>Promjena termina od strane Natura Sanat</h2><p>Ako Sandra mora promijeniti ili otkazati termin, bit ćete obaviješteni što je prije moguće i ponuđen će vam biti zamjenski termin bez dodatnog troška. Ako vam zamjenski termin ne odgovara, vraća se puni iznos plaćen za neizvršenu uslugu. Kod programa se vraća razmjeran iznos za neodržane termine.</p>
<h2>Neiskorištena usluga ili program</h2><p>Usluga se koristi u dogovorenim terminima i rokovima. Ako je ne možete nastaviti, javite se što prije. Za već pružene termine, obavljenu individualnu pripremu i isporučene materijale nema povrata, osim kada primjenjivi zakon određuje drukčije. Za neizvršeni dio programa mogućnost povrata ili zamjenskog termina procjenjuje se prema trenutku otkazivanja i ovim uvjetima.</p>
<h2>Usluga ugovorena na daljinu</h2><p>Prije prihvata dobivate podatke o pružatelju, sadržaju, cijeni, trajanju, načinu izvršenja i primjenjivom pravu na jednostrani raskid. Ako želite da pružanje usluge započne prije isteka zakonskog roka za jednostrani raskid, od vas se zasebno traži izričit zahtjev i potvrda posljedica takvog zahtjeva. Kućica nije unaprijed označena.</p>
<h2>Digitalni vodiči</h2><p>Digitalni vodič namijenjen je osobnoj uporabi kupca. Ne smije se dijeliti, preprodavati, javno objavljivati ili učiniti dostupnim drugim osobama. Nakon potvrđene uplate kupac na adresu unesenu pri plaćanju dobiva vremenski ograničenu poveznicu za standardnu PDF datoteku kupljenog izdanja.</p><p>Poveznica za preuzimanje vrijedi 48 sati i omogućuje najviše tri preuzimanja. Poveznica je vezana uz potvrđenu Stripe narudžbu, ali sama PDF datoteka trenutačno nije personalizirana imenom kupca niti brojem narudžbe.</p><p>Kada kupac zatraži trenutačnu isporuku digitalnog sadržaja prije isteka roka za jednostrani raskid, zasebno potvrđuje izričit pristanak na početak isporuke i svijest o zakonskim posljedicama. Zakonska prava u slučaju neispravnog ili neusklađenog digitalnog sadržaja ostaju očuvana.</p>
<h2>Opseg i granice savjetovanja</h2><p>Usluge i sadržaji edukativnog su i savjetodavnog karaktera. Ne uključuju dijagnostiku, liječenje, propisivanje lijekova ili promjenu terapije. Kod postojećeg zdravstvenog stanja savjetovanje se provodi komplementarno uz liječenje i preporuke nadležnog zdravstvenog tima.</p>
<h2>Prigovori</h2><p>Na pisani prigovor odgovara se u zakonskom roku. Detaljne upute dostupne su na stranici <a href="/prigovori-i-povrati">Prigovori i povrati</a>.</p>
</LegalPage>}
