import {LegalPage} from "../legal-page";
export default function Page(){return <LegalPage title="Uvjeti usluga i buduće kupnje" intro="Nacrt za pravnu provjeru. Na webu trenutačno nema naplate ni isporuke digitalnih proizvoda.">
<h2>Pružatelj usluge</h2><p>Natura Sanat, obrt za nutricionističko i fitoaromaterapijsko savjetovanje, vl. Sandra Pavić Drašković, Zelenjak 38, 10000 Zagreb. OIB: 77515854476. MBO: 98353055.</p><p>Za kontakt koristi <a href="/kontakt">kontaktni obrazac</a>. Pisani prigovor može se poslati i na navedenu poštansku adresu. Aktualnost podataka treba potvrditi.</p>
<h2>Opseg savjetovanja</h2><p>Usluge su edukativne i namijenjene punoljetnim osobama. Opseg, trajanje, način održavanja, ukupna cijena i uključeni materijali navode se u ponudi prije prihvata. Savjetovanje ne uključuje dijagnostiku, propisivanje liječenja ili promjenu terapije.</p>
<h2>Ugovaranje i cijena</h2><p>Slanje upita nije kupnja ni rezervacija. Prije ugovaranja korisnik dobiva ponudu i relevantne obavijesti na trajnom mediju. Za dodatnu uslugu ili dulji termin potrebni su obavijest o cijeni i prethodni dogovor, a ne automatska naknadna naplata.</p>
<h2>Promjena termina i raskid</h2><p>Politiku otkazivanja, rokove i eventualne naknade treba potvrditi u ponudi prije prihvata. Oni ne smiju isključiti zakonska prava potrošača. Za ugovaranje na daljinu potrebno je dati obavijest o pravu na jednostrani raskid i obrazac. Ako se traži početak usluge prije isteka tog roka, potrebne izjave prikupljaju se zasebno, u skladu s primjenjivim propisima.</p>
<h2>Digitalni sadržaj</h2><p>Knjižice su najavljene, ali nisu dostupne za kupnju. Prije početka prodaje objavit će se konačna cijena, format, tehnički zahtjevi, način i rok isporuke te podrška. Prije prelaska na plaćanje kupac mora zasebno potvrditi prihvat uvjeta, čitanje obavijesti o privatnosti, edukativnu prirodu sadržaja te, kada traži trenutačnu isporuku, izričito zatražiti početak isporuke i potvrditi posljedice za pravo na jednostrani raskid. Kućice nisu unaprijed označene.</p><p>Uz narudžbu se mora evidentirati proizvod, verzija prihvaćenih uvjeta i izjava, datum i vrijeme potvrde te podaci nužni za dokazivanje kupnje. Zakonska prava zbog neusklađenog digitalnog sadržaja ostaju očuvana. Točan tekst i rokove čuvanja evidencije potrebno je potvrditi prije uključivanja prodaje.</p>
<h2>Prigovori</h2><p>Na pisani prigovor potrošača odgovara se u zakonskom roku, trenutačno 15 dana od primitka. Postupak potvrde primitka i evidencije prigovora potrebno je operativno uspostaviti.</p>
<h2>Odgovornost</h2><p>Osobno iskustvo i edukativni sadržaji nisu jamstvo zdravstvenog rezultata. Napomena da savjetovanje nije liječenje ne isključuje prava korisnika ni odgovornost koju prema zakonu nije dopušteno isključiti.</p>
<h2>Autorska prava</h2><p>Za korištenje tekstova, fotografija i budućih digitalnih proizvoda vrijede pripadajuća autorska prava. Dopušteni opseg korištenja digitalnog izdanja navest će se prije kupnje.</p>
<h2>Izvori za pravnu provjeru</h2><p><a href="https://narodne-novine.nn.hr/clanci/sluzbeni/2022_02_19_203.html">Zakon o zaštiti potrošača</a>, uključujući kasnije izmjene, te <a href="https://narodne-novine.nn.hr/clanci/sluzbeni/2021_10_110_1925.html">pravila za digitalni sadržaj i usluge</a>. Konačna provjera mora obuhvatiti i izmjene propisa iz 2026.</p></LegalPage>}
