import Image from "next/image";
import {Header, Footer} from "./site-components";
import {DigitalConsentGate} from "./digital-consent-gate";

const guides = [
  {id:"biljna-prehrana", checkoutUrl:process.env.NEXT_PUBLIC_CHECKOUT_BILJNA_PREHRANA, title:"Moja antikancerogena, bezglutenska biljna prehrana", coverImage:"/images/kuharica/moja-antikancerogena-bezglutenska-biljna-prehrana-final.jpg", subtitle:"Autorski vodič kroz moj pristup biljnoj prehrani + 50 recepata", count:50, pages:72, price:49, listed:"24. 9. 2026.", kind:"Edukativni vodič + recepti", text:"Sandrin osobni pristup biljnoj prehrani: od izbora i pripreme namirnica do slaganja svakodnevnih obroka. Znanje i iskustvo povezuje s receptima koje je uključivala u vlastitu svakodnevicu.", topics:["Načela Sandrine biljne prehrane", "Izbor namirnica, priprema i slaganje obroka", "Očuvanje nutritivne vrijednosti tijekom pripreme", "Bezglutenski i pretežno niskomasni recepti", "Juhe, variva, glavna jela, salate, prilozi i namazi"]},
  {id:"svjeza-prehrana", checkoutUrl:process.env.NEXT_PUBLIC_CHECKOUT_SVJEZA_PREHRANA, title:"Smoothie, sokovi i sirove juhe", coverImage:"/images/kuharica/smoothie-sokovi-sirove-juhe-final.jpg", subtitle:"Vodič kroz svježu biljnu prehranu + 27 recepata", count:27, pages:49, price:39, listed:"24. 9. 2026.", kind:"Edukativni vodič + recepti", text:"Upoznaj razliku između sokova i smoothieja, izbor namirnica te postupke pripreme i čuvanja. Edukativni dio prati 27 recepata za uključivanje svježih biljnih namirnica u svakodnevnu prehranu.", topics:["Razlika između sokova i smoothieja", "Izbor i kombiniranje namirnica", "Priprema i čuvanje", "Smoothieji, svježi sokovi i sirove juhe"]},
  {id:"blagdanski-recepti", checkoutUrl:process.env.NEXT_PUBLIC_CHECKOUT_BLAGDANSKI_RECEPTI, title:"Biljna inspiracija za blagdanski stol", coverImage:"/images/kuharica/biljna-inspiracija-blagdanski-stol-final.jpg", subtitle:"25 recepata za zdraviju i kreativniju biljnu blagdansku trpezu", count:25, pages:32, price:34, listed:"30. 9. 2026.", kind:"Blagdanska kolekcija recepata", text:"Recepti iz Sandrine kuhinje nastali kao inspiracija svima koji i tijekom blagdana žele uživati u kreativnoj, biljnoj i pažljivo pripremljenoj hrani.", topics:["Predjela i dvije varijante francuske salate", "Glavna jela", "Krekeri, kruh i namazi", "Blagdanske slastice"]},
];

export function GuideCatalog(){return <><Header/><main className="guides-page">
  <section className="wrap guides-intro"><p className="eyebrow">Natura Sanat kolekcija vodiča i recepata</p><h1>Više od recepata.</h1><p className="lede">Znanje, iskustvo i recepti koje sam godinama stvarala, proučavala i primjenjivala na svojem putu prema zdravlju.</p><p>Ova digitalna izdanja nastala su iz želje da na jednom mjestu prenesem ono što sam kroz godine učila o biljnoj prehrani, pripremi hrane, kombiniranju namirnica i stvaranju obroka koji su istovremeno nutritivno bogati, jednostavni i ukusni.</p><p className="guides-author">Sandra Pavić Drašković, mag. pharm.</p><div className="guides-facts"><span><strong>3</strong> digitalna izdanja</span><span><strong>102</strong> recepta</span><span><strong>2</strong> edukativna vodiča + blagdanska kolekcija</span></div><p className="fine">Online kupnja i sigurna dostava personaliziranih izdanja uključit će se nakon završne provjere naplate i datoteka.</p></section>
  <section className="guides-list stone"><div className="wrap"><header><p className="eyebrow">Uči. Pripremi. Isprobaj.</p><h2>Od razumijevanja namirnica do tvoje kuhinje.</h2><p>Prva dva izdanja povezuju edukaciju s receptima. Treće donosi blagdansku inspiraciju. Svako možeš čitati svojim tempom i vraćati mu se kad pripremaš obroke.</p></header>
  {guides.map((guide,i)=><article className="guide-product" id={guide.id} key={guide.id}><div className="guide-cover-image-wrap"><Image className="guide-cover-image" src={guide.coverImage} alt={`Naslovnica e-knjige ${guide.title}`} width={744} height={1053} sizes="(max-width: 1000px) 90vw, 42vw" priority={i===0}/></div><div className="guide-details"><p className="eyebrow">{guide.kind}</p><h2>{guide.subtitle}</h2><p>{guide.text}</p><h3>Što te čeka u izdanju</h3><ul>{guide.topics.map(topic=><li key={topic}>{topic}</li>)}</ul><div className="guide-price"><div><span className="guide-price-label">Trenutna cijena</span><strong>{guide.price} €</strong></div><span><b>{guide.count} recepata</b><br/>{guide.pages?`${guide.pages} stranice · `:""}digitalno izdanje</span><p className="statutory-anchor">Cijena pri prvom uvrštenju {guide.listed}: <strong>{guide.price} €</strong></p></div><DigitalConsentGate product={guide.title} price={guide.price} checkoutUrl={guide.checkoutUrl}/>{i===0&&<p className="fine guide-title-note">Naveden je izvorni naslov autorice. Osobno iskustvo nije jamstvo ishoda; vodič ne služi liječenju ili sprječavanju raka i ne zamjenjuje propisanu terapiju.</p>}</div></article>)}
  </div></section>
  <section className="wrap guide-collection"><div><p className="eyebrow">Sandrina kompletna kolekcija</p><h2>Znanje i inspiracija.<br/>Na jednom mjestu.</h2><p>Dva opsežnija edukativna vodiča s receptima i blagdanska kolekcija biljnih recepata: sva tri digitalna izdanja s ukupno 102 recepta.</p><ul>{guides.map(guide=><li key={guide.id}>{guide.title}<span>{guide.count} recepata</span></li>)}</ul></div><div className="collection-price"><span className="collection-badge">Najbolja vrijednost</span><p>3 e-knjige · 102 recepta</p><div className="collection-anchor"><span>Pojedinačna vrijednost</span><span>122 €</span></div><div className="collection-current"><span>Cijela kolekcija</span><strong>100 €</strong></div><p className="statutory-anchor statutory-anchor-dark">Cijena pri prvom uvrštenju 30. 9. 2026.: <strong>100 €</strong></p><p className="collection-saving">Ušteda u odnosu na pojedinačnu kupnju: 22 €</p><DigitalConsentGate product="Sandrina kompletna kolekcija: 3 e-knjige" price={100} checkoutUrl={process.env.NEXT_PUBLIC_CHECKOUT_KOLEKCIJA}/></div></section>
  <section className="stone guides-closing"><div className="wrap"><h2>Otvori kad ti zatreba. Vrati se kad kuhaš.</h2><p>Vodiči okupljaju Sandrino znanje o biljnoj prehrani, iskustvo pripreme hrane i recepte iz njezine svakodnevice.</p><a className="arrow-link" href="/sandra">Upoznaj autoricu →</a></div></section>
</main><Footer/></>}
