import Image from "next/image";
import {Header, Footer} from "./site-components";
import {DigitalConsentGate} from "./digital-consent-gate";

const guides = [
  {id:"biljna-prehrana", checkoutUrl:process.env.NEXT_PUBLIC_CHECKOUT_BILJNA_PREHRANA, title:"Moja antikancerogena, bezglutenska biljna prehrana", coverImage:"/images/kuharica/moja-antikancerogena-bezglutenska-biljna-prehrana-cover.jpg", coverLines:["Moja antikancerogena,","bezglutenska biljna","prehrana"], subtitle:"Moj osobni put prema zdravlju kroz prehranu", count:50, pages:72, price:49, kind:"Edukativni vodič + recepti", text:"Sandrin osobni pristup biljnoj prehrani: od izbora i pripreme namirnica do slaganja svakodnevnih obroka. Znanje i iskustvo povezuje s receptima koje je uključivala u vlastitu svakodnevicu.", topics:["Načela Sandrine biljne prehrane", "Izbor namirnica, priprema i slaganje obroka", "Očuvanje nutritivne vrijednosti tijekom pripreme", "Bezglutenski i pretežno niskomasni recepti", "Juhe, variva, glavna jela, salate, prilozi i namazi"]},
  {id:"svjeza-prehrana", checkoutUrl:process.env.NEXT_PUBLIC_CHECKOUT_SVJEZA_PREHRANA, title:"Smoothie, sokovi i sirove juhe", coverLines:["Smoothie, sokovi","i sirove juhe"], subtitle:"Vodič kroz svježu biljnu prehranu", count:27, price:39, kind:"Edukativni vodič + recepti", text:"Upoznaj razliku između sokova i smoothieja, izbor namirnica te postupke pripreme i čuvanja. Edukativni dio prati 27 recepata za uključivanje svježih biljnih namirnica u svakodnevnu prehranu.", topics:["Razlika između sokova i smoothieja", "Izbor i kombiniranje namirnica", "Priprema i čuvanje", "Smoothieji, svježi sokovi i sirove juhe"]},
  {id:"blagdanski-recepti", checkoutUrl:process.env.NEXT_PUBLIC_CHECKOUT_BLAGDANSKI_RECEPTI, title:"Knjižica blagdanskih recepata", coverLines:["Knjižica","blagdanskih recepata"], subtitle:"Biljna inspiracija za blagdanski stol", count:25, price:29, kind:"Blagdanska zbirka recepata", text:"Raznolika, kreativna i ukusna biljna trpeza za dane okupljanja. Zbirka je usmjerena na recepte i praktičnu inspiraciju za blagdane.", topics:["Predjela i dvije varijante francuske salate", "Glavna jela", "Krekeri, kruh i namazi", "Blagdanske slastice"]},
];

export function GuideCatalog(){return <><Header/><main className="guides-page">
  <section className="wrap guides-intro"><p className="eyebrow">E-knjige · edukativni vodiči s receptima</p><h1>Više od recepata.</h1><p className="lede">Znanje i recepti s mog osobnog puta prema zdravlju.</p><p>„Ono što sam učila. Ono što sam primjenjivala. Ono što danas prenosim drugima.“</p><p className="guides-author">Sandra Drašković · magistra farmacije i fitoaromaterapeutkinja</p><div className="guides-facts"><span><strong>3</strong> digitalna izdanja</span><span><strong>102</strong> recepta</span><span><strong>2</strong> edukativna vodiča + blagdanska zbirka</span></div><p className="fine">Ponuda u radnom pregledu. Online kupnja i dostava e-knjiga još nisu uključene.</p></section>
  <section className="guides-list stone"><div className="wrap"><header><p className="eyebrow">Uči. Pripremi. Isprobaj.</p><h2>Od razumijevanja namirnica do tvoje kuhinje.</h2><p>Prva dva izdanja povezuju edukaciju s receptima. Treće donosi blagdansku inspiraciju. Svako možeš čitati svojim tempom i vraćati mu se kad pripremaš obroke.</p></header>
  {guides.map((guide,i)=><article className="guide-product" id={guide.id} key={guide.id}>{guide.coverImage?<div className="guide-cover-image-wrap"><Image className="guide-cover-image" src={guide.coverImage} alt={`Naslovnica e-knjige ${guide.title}`} width={744} height={1053} sizes="(max-width: 1000px) 90vw, 42vw" priority={i===0}/></div>:<div className={`guide-cover guide-cover-${i}`} aria-label={`Prikaz naslovnice: ${guide.title}`}><span>Natura Sanat<br/>Sandra Drašković</span><h3>{guide.coverLines.map(line=><span key={line}>{line}</span>)}</h3><div><strong>{guide.count}</strong><span>recepata</span></div><span>{guide.kind}</span></div>}<div className="guide-details"><p className="eyebrow">{guide.kind}</p><h2>{guide.subtitle}</h2><p>{guide.text}</p><h3>Što te čeka u izdanju</h3><ul>{guide.topics.map(topic=><li key={topic}>{topic}</li>)}</ul><div className="guide-price"><div><span className="guide-price-label">Trenutna cijena</span><strong>{guide.price} €</strong></div><span><b>{guide.count} recepata</b><br/>{guide.pages?`${guide.pages} stranice · `:""}digitalno izdanje</span><p className="statutory-anchor">Cijena pri prvom uvrštenju 24. 9. 2026.: <strong>{guide.price} €</strong></p></div><DigitalConsentGate product={guide.title} price={guide.price} checkoutUrl={guide.checkoutUrl}/>{i===0&&<p className="fine guide-title-note">Naveden je izvorni naslov autorice. Osobno iskustvo nije jamstvo ishoda; vodič ne služi liječenju ili sprječavanju raka i ne zamjenjuje propisanu terapiju.</p>}</div></article>)}
  </div></section>
  <section className="wrap guide-collection"><div><p className="eyebrow">Sandrina kompletna kolekcija</p><h2>Znanje i inspiracija.<br/>Na jednom mjestu.</h2><p>Dva edukativna vodiča i blagdanska zbirka: sva tri digitalna izdanja s ukupno 102 recepta.</p><ul>{guides.map(guide=><li key={guide.id}>{guide.title}<span>{guide.count} recepata</span></li>)}</ul></div><div className="collection-price"><span className="collection-badge">Najbolja vrijednost</span><p>3 e-knjige · 102 recepta</p><div className="collection-anchor"><span>Zbroj pojedinačnih cijena</span><span>117 €</span></div><div className="collection-current"><span>Trenutna cijena kolekcije</span><strong>99 €</strong></div><p className="statutory-anchor statutory-anchor-dark">Cijena pri prvom uvrštenju 24. 9. 2026.: <strong>99 €</strong></p><p className="collection-saving">Ušteda u odnosu na pojedinačnu kupnju: 18 €</p><DigitalConsentGate product="Kompletna kolekcija: 3 e-knjige" price={99} checkoutUrl={process.env.NEXT_PUBLIC_CHECKOUT_KOLEKCIJA}/></div></section>
  <section className="stone guides-closing"><div className="wrap"><h2>Otvori kad ti zatreba. Vrati se kad kuhaš.</h2><p>Vodiči okupljaju Sandrino znanje o biljnoj prehrani, iskustvo pripreme hrane i recepte iz njezine svakodnevice.</p><a className="arrow-link" href="/sandra">Upoznaj autoricu →</a></div></section>
</main><Footer/></>}
