import Image from "next/image";
import {Header, Footer} from "./site-components";
import {DigitalConsentGate} from "./digital-consent-gate";

const guides = [
  {id:"biljna-prehrana", checkoutUrl:process.env.NEXT_PUBLIC_CHECKOUT_BILJNA_PREHRANA, title:"Hrana za buđenje životne energije i vitalnosti", coverImage:"/images/kuharica/hrana-zivotna-energija-vitalnost-final.jpg", subtitle:"Vodič kroz prehranu za energiju, zdravlje, ravnotežu i vitalnost", count:50, pages:72, price:49, listed:"24. 9. 2026.", kind:"Edukativni vodič · 50 biljnih i bezglutenskih recepata", text:"Praktičan vodič koji povezuje Sandrino stručno znanje, osobno iskustvo i svakodnevnu biljnu prehranu. Od razumijevanja namirnica i slaganja obroka vodi do 50 recepata za raznoliku, jednostavnu i ukusnu svakodnevicu.", topics:["Temelji uravnotežene biljne prehrane", "Izbor namirnica, priprema i slaganje obroka", "Očuvanje nutritivne vrijednosti tijekom pripreme", "Energija, ravnoteža i održive svakodnevne navike", "50 biljnih i bezglutenskih recepata za juhe, variva, glavna jela, salate, priloge i namaze"]},
  {id:"svjeza-prehrana", checkoutUrl:process.env.NEXT_PUBLIC_CHECKOUT_SVJEZA_PREHRANA, title:"Snaga svježine", coverImage:"/images/kuharica/smoothie-sokovi-sirove-juhe-final-v2.jpg", subtitle:"Sokovi, smoothieji i sirove juhe za energiju, svježinu i vitalnost", count:27, pages:49, price:39, listed:"24. 9. 2026.", kind:"Edukativni vodič · 27 biljnih i bezglutenskih recepata", text:"Upoznaj razliku između sokova i smoothieja, izbor namirnica te postupke pripreme i čuvanja. Edukativni dio prati 27 recepata za uključivanje svježih biljnih namirnica u svakodnevnu prehranu.", topics:["Razlika između sokova i smoothieja", "Izbor i kombiniranje namirnica", "Priprema i čuvanje", "21 smoothie, 6 sirovih juha te voćni i povrtni sokovi"]},
  {id:"blagdanski-recepti", checkoutUrl:process.env.NEXT_PUBLIC_CHECKOUT_BLAGDANSKI_RECEPTI, title:"Blagdanski okusi", coverImage:"/images/kuharica/biljna-inspiracija-blagdanski-stol-final-v2.jpg", subtitle:"25 biljnih i bezglutenskih recepata za kreativniju blagdansku trpezu", count:25, pages:32, price:34, listed:"30. 9. 2026.", kind:"Blagdanska kolekcija · 25 recepata", text:"Recepti iz Sandrine kuhinje nastali kao inspiracija svima koji i tijekom blagdana žele uživati u kreativnoj, biljnoj i pažljivo pripremljenoj hrani.", topics:["Predjela i dvije varijante francuske salate", "Glavna jela", "Krekeri, kruh i namazi", "Blagdanske slastice"]},
];

export function GuideCatalog(){return <><Header/><main className="guides-page">
  <section className="wrap guides-intro"><p className="eyebrow">Natura Sanat kolekcija vodiča i recepata</p><h1>Više od recepata.</h1><p className="lede">Znanje, iskustvo i recepti koje sam godinama stvarala, proučavala i primjenjivala na svojem putu prema zdravlju.</p><p>Ova digitalna izdanja nastala su iz želje da na jednom mjestu prenesem ono što sam kroz godine učila o biljnoj prehrani, pripremi hrane, kombiniranju namirnica i stvaranju obroka koji su istovremeno nutritivno bogati, jednostavni i ukusni.</p><p className="guides-author">Sandra Pavić Drašković, mag. pharm.</p><div className="guides-facts"><span><strong>3</strong> digitalna izdanja</span><span><strong>102</strong> recepta</span><span><strong>2</strong> edukativna vodiča + blagdanska kolekcija</span></div><p className="fine">Online kupnja i sigurna dostava personaliziranih izdanja uključit će se nakon završne provjere naplate i datoteka.</p></section>
  <section className="guides-list stone"><div className="wrap"><header><p className="eyebrow">Uči. Pripremi. Isprobaj.</p><h2>Od razumijevanja namirnica do tvoje kuhinje.</h2><p>Prva dva izdanja povezuju edukaciju s receptima. Treće donosi blagdansku inspiraciju. Svako možeš čitati svojim tempom i vraćati mu se kad pripremaš obroke.</p></header>
  {guides.map((guide,i)=><article className="guide-product" id={guide.id} key={guide.id}><div className="guide-cover-image-wrap"><Image className="guide-cover-image" src={guide.coverImage} alt={`Naslovnica e-knjige ${guide.title}`} width={1190} height={1684} sizes="(max-width: 1000px) 90vw, 42vw" priority={i===0}/></div><div className="guide-details"><p className="eyebrow">{guide.kind}</p><h2>{guide.title}</h2><p className="guide-subtitle">{guide.subtitle}</p><p>{guide.text}</p><h3>Što te čeka u izdanju</h3><ul>{guide.topics.map(topic=><li key={topic}>{topic}</li>)}</ul><div className="guide-price"><div><span className="guide-price-label">Trenutna cijena</span><strong>{guide.price} €</strong></div><span><b>{guide.count} recepata</b><br/>{guide.pages?`${guide.pages} stranice · `:""}digitalno izdanje</span><p className="statutory-anchor">Cijena pri prvom uvrštenju {guide.listed}: <strong>{guide.price} €</strong></p></div><DigitalConsentGate product={guide.title} price={guide.price} checkoutUrl={guide.checkoutUrl}/></div></article>)}
  </div></section>
  <section className="wrap guide-collection" id="kompletna-kolekcija"><div><p className="eyebrow">Sandrina kompletna kolekcija</p><h2>Znanje i inspiracija.<br/>Na jednom mjestu.</h2><p>Dva opsežnija edukativna vodiča s receptima i blagdanska kolekcija biljnih recepata: sva tri digitalna izdanja s ukupno 102 recepta.</p><ul>{guides.map(guide=><li key={guide.id}>{guide.title}<span>{guide.count} recepata</span></li>)}</ul></div><div className="collection-price"><span className="collection-badge">Kompletna kolekcija</span><p>3 e-knjige · 102 recepta</p><div className="collection-anchor"><span>Pojedinačna vrijednost</span><span>122 €</span></div><div className="collection-current"><span>Cijela kolekcija</span><strong>100 €</strong></div><p className="statutory-anchor statutory-anchor-dark">Cijena pri prvom uvrštenju 30. 9. 2026.: <strong>100 €</strong></p><DigitalConsentGate product="Sandrina kompletna kolekcija: 3 e-knjige" price={100} checkoutUrl={process.env.NEXT_PUBLIC_CHECKOUT_KOLEKCIJA}/></div></section>
  <section className="stone guides-closing"><div className="wrap"><h2>Otvori kad ti zatreba. Vrati se kad kuhaš.</h2><p>Vodiči okupljaju Sandrino znanje o biljnoj prehrani, iskustvo pripreme hrane i recepte iz njezine svakodnevice.</p><a className="arrow-link" href="/sandra">Upoznaj autoricu →</a></div></section>
</main><Footer/></>}
