import Link from "next/link";import {Header,Footer,ArrowLink} from "./site-components";
const paths=[["01","Želim bolje razumjeti što mi treba.","Health Review","90 min · individualno","120 €","/health-review"],["02","Želim napraviti ozbiljniju promjenu.","Health Reset","6 tjedana · grupni program","329 €","/health-reset"],["03","Vraćam se sebi nakon liječenja.","After Treatment","Individualni pristup","TODO_CONFIRM_WITH_SANDRA","/health-review"]];
const articles=[["Trebaš li stvarno detox?","Što tijelo već radi samo i gdje zdrave promjene stvarno počinju."],["Magnezij nije samo magnezij.","Različiti oblici, različite namjene i zašto nije dobro birati samo prema Instagram preporuci."],["Ne moraš biti bolestan da bi promijenio način života.","Zašto prevencija nije isto što i strah od bolesti."]];
export default function Home(){return <><Header/><main>
<section className="hero wrap"><div className="hero-copy reveal"><p className="eyebrow">Prehrana · biljke · zdrave navike</p><h1>Brini o zdravlju prije nego što moraš.</h1><p className="lede">Prehrana, suplementi, biljke i svakodnevne navike objašnjeni farmaceutskim znanjem, iskustvom i bez ekstremnih rješenja.</p><p className="signature"><strong>Sandra Pavić Drašković</strong><span>mag. pharm. · fitoaromaterapeutkinja · edukatorica</span></p><div className="actions"><Link className="button" href="#pocni">Pronađi svoj sljedeći korak</Link><ArrowLink href="/sandra">Upoznaj Sandru</ArrowLink></div><p className="micro">Individualni rad · programi · predavanja</p></div><div className="portrait reveal delay" role="img" aria-label="Mjesto za editorial portret Sandre Pavić Drašković"><span>Editorial portrait</span><small>Fotografija Sandre<br/>TODO_CONFIRM_WITH_SANDRA</small></div></section>
<div className="trust"><div className="wrap trust-grid"><span>Magistra farmacije</span><span>Individualni rad i edukacija</span><span>Predavanja i radionice</span><span>Iskustvo zdravlja iz obje perspektive</span></div></div>
<section className="section wrap split"><div><p className="eyebrow">Zdravlje ne počinje dijagnozom</p><h2>Ne moraš biti bolestan da bi počeo brinuti o sebi.</h2></div><div className="body-copy"><p>Većina ljudi ozbiljno razmišlja o prehrani, snu, stresu i životnim navikama tek kada nešto postane problem.</p><p className="serif-line">Ne mora biti tako.</p><p>Sandra radi s ljudima koji žele bolje razumjeti vlastito zdravlje, prepoznati što im je stvarno važno i napraviti promjene koje mogu održati.</p><p className="closing">Bez savršenih jelovnika.<br/>Bez straha.<br/>Bez čudotvornih rješenja.</p></div></section>
<section id="pocni" className="section stone"><div className="wrap"><p className="eyebrow">Počni ovdje</p><h2>Što želiš promijeniti?</h2><div className="paths">{paths.map((p,i)=><article className="path" key={p[0]}><span className="path-number">{p[0]}</span><h3>{p[1]}</h3><div><strong>{p[2]}</strong><p>{p[3]}</p><b className={i===2?"todo":""}>{p[4]}</b></div><ArrowLink href={p[5]}>{i===0?"Kako funkcionira Health Review":i===1?"Upoznaj Health Reset":"Saznaj više"}</ArrowLink></article>)}</div></div></section>
<section className="section wrap b2b"><div><p className="eyebrow">Za tvrtke i organizacije</p><h2>Trebate predavanje koje ljudi neće zaboraviti čim izađu iz dvorane?</h2></div><div><p>Predavanja i radionice o prehrani, suplementima, životnim navikama i zdravstvenoj pismenosti — jasno, praktično i bez wellness klišeja.</p><ArrowLink href="/predavanja">Predavanja i radionice</ArrowLink><p className="micro">od 450 €</p></div></section>
<section className="section about"><div className="wrap about-grid"><div className="about-mark"><span>SPD</span></div><div><p className="eyebrow">O Sandri</p><h2>Znanje je bilo početak. Iskustvo je promijenilo perspektivu.</h2><div className="body-copy"><p>Sandra Pavić Drašković je magistra farmacije, fitoaromaterapeutkinja i edukatorica.</p><p>Farmaceutsko obrazovanje dalo joj je stručnu osnovu. Ozbiljna vlastita bolest godinama kasnije promijenila je način na koji promatra prehranu, životne navike i odnos prema zdravlju.</p><p>Umjesto da jedno zamijeni drugim, nastavila je učiti.</p><p>Danas svoj rad gradi između stručnog znanja i iskustva stvarnog života.</p><p>Njezin cilj nije uvjeriti ljude da postoji jedno rješenje za sve, nego pomoći im razumjeti što ima smisla za njih — i što mogu stvarno primijeniti.</p></div><ArrowLink href="/sandra">Upoznaj Sandru</ArrowLink></div></div></section>
<figure className="quote wrap"><blockquote>“Najbolji plan za zdravlje nije onaj koji možeš izdržati tri tjedna. Nego onaj koji možeš živjeti.”</blockquote><figcaption>— Sandra <span>predloženi brand copy</span></figcaption></figure>
<section className="section reset"><div className="wrap reset-grid"><div><p className="eyebrow">Signature program</p><p className="program-name">Health Reset</p><h2>Šest tjedana za sustav koji možeš stvarno živjeti.</h2><p>Ne treba ti još jedna lista stvari koje ne smiješ jesti. Treba ti razumijevanje što ti je prioritet, što možeš pojednostaviti i koje promjene imaju najveću vrijednost.</p><div className="actions"><Link className="button" href="/health-reset">Istraži Health Reset</Link><ArrowLink href="/health-reset">Pridruži se listi čekanja</ArrowLink></div><p className="micro">Sljedeća grupa: uskoro</p></div><ol className="pillars">{["Prehrana","Energija","San","Kretanje","Stres","Suplementi i biljke"].map((x,i)=><li key={x}><span>0{i+1}</span>{x}</li>)}</ol></div></section>
<section className="section wrap reposition"><p className="eyebrow">Što Health Reset nije</p><h2>Ovo nije još jedan “detox izazov”.</h2><p>Health Reset nije brzo mršavljenje, gladovanje, univerzalni jelovnik ni čudotvorno čišćenje organizma.</p><p>To je strukturirano vrijeme u kojem prestajemo juriti savršeno zdravlje i počinjemo graditi bolji sustav svakodnevnih odluka.</p></section>
<section className="section stone"><div className="wrap"><div className="knowledge-intro"><div><p className="eyebrow">Znanje</p><h2>Sandra objašnjava.</h2></div><div><p>Internet ima dovoljno zdravstvenih savjeta.</p><p>Ovdje pokušavamo odgovoriti na važnije pitanje:</p><p className="serif-line">Što od toga stvarno ima smisla?</p></div></div><div className="articles">{articles.map((a,i)=><article key={a[0]}><span>0{i+1}</span><h3>{a[0]}</h3><p>{a[1]}</p><ArrowLink href="/znanje">Čitaj bilješku</ArrowLink></article>)}</div></div></section>
<section className="section wrap pharmacy"><div><p className="eyebrow">Manje nasumičnih odluka</p><h2>“Prirodno” ne znači automatski potrebno. Ni bezopasno.</h2><p>Dodaci prehrani i biljni pripravci danas su dostupniji nego ikada. To ne znači da ih trebamo koristiti bez konteksta.</p></div><ul><li>zašto nešto uzimaš</li><li>što već koristiš</li><li>gdje postoje moguće interakcije</li><li>što možda uopće nije prioritet</li></ul></section>
<section className="section speaking"><div className="wrap speaking-grid"><div><p className="eyebrow">Predavanja & radionice</p><h2>Znanje koje ostaje korisno i nakon predavanja.</h2><ArrowLink href="/predavanja">Pozovite Sandru</ArrowLink><p className="micro">Predavanja od 450 €</p></div><ol>{["Zdravlje prije problema","Supplement Smarter","Health After 40","Prehrana u stvarnom životu"].map((x,i)=><li key={x}><span>0{i+1}</span>{x}</li>)}</ol></div></section>
<section className="section newsletter wrap"><div><p className="eyebrow">Bilješke o zdravlju</p><h2>Jedno korisno pismo. Dva puta mjesečno.</h2><p>Jedna tema o prehrani, suplementima, biljkama ili svakodnevnim navikama — bez senzacionalizma i bez buke.</p></div><form className="email-form"><label htmlFor="email">Tvoj email</label><div><input id="email" type="email" placeholder="ime@email.com"/><button type="button">Želim Sandrine bilješke</button></div><small>TODO_CONFIRM_WITH_SANDRA · integracija newslettera</small></form></section>
<section className="final-cta"><div className="wrap"><h2>Ne trebaš promijeniti sve.</h2><h3>Trebaš znati odakle krenuti.</h3><div className="actions"><Link className="button light" href="/health-review">Rezerviraj Health Review — 120 €</Link><ArrowLink href="#pocni">Istraži sve načine rada sa Sandrom</ArrowLink></div></div></section>
</main><Footer/></>}
