import type {Metadata} from "next";
import Image from "next/image";
import {featuredTestimonials} from "./_data/testimonials";
import {services} from "./_data/services";
import {ArrowLink,Footer,Header} from "./site-components";

export const metadata:Metadata={title:"Natura Sanat | Individualno savjetovanje i programi",description:"Individualno savjetovanje Sandre Pavić Drašković o prehrani, suplementaciji i zdravim životnim navikama, online ili u Zagrebu.",alternates:{canonical:"/"}};

const audiences=[
  {icon:"🌱",title:"Želim očuvati zdravlje i vitalnost",text:"Želite se kvalitetnije hraniti, djelovati preventivno, imati više energije i usvojiti zdrave navike koje možete dugoročno primjenjivati."},
  {icon:"🥗",title:"Želim ostvariti svoj osobni cilj",text:"Želite regulirati tjelesnu težinu, promijeniti način prehrane, prijeći na biljnu ili sirovu prehranu ili prehranu prilagoditi sportu."},
  {icon:"🤍",title:"Želim dodatnu podršku svojem zdravlju",text:"Želite prehranu, dodatke, fitoaromaterapiju i navike prilagoditi svojem trenutačnom zdravstvenom stanju, uz poštovanje liječničke terapije."},
];

export default function Home(){return <><Header/><main>
  <section className="ns-hero"><Image src="/editorial-produce.png" alt="Svježe povrće i biljne namirnice" fill priority sizes="100vw"/><div className="ns-hero-shade"/><div className="ns-hero-copy"><p className="kicker">Natura Sanat</p><h1>Holistički put zdravlja sa Sandrom Pavić Drašković</h1><p>Individualno savjetovanje o prehrani, dodacima i zdravim životnim navikama za očuvanje zdravlja, osobne ciljeve i podršku usklađenu s vašim trenutačnim stanjem.</p><div className="actions"><a className="button" href="/savjetovanje">Započnite ovdje</a><a className="button button-ghost" href="/sandra">Upoznajte me</a></div></div></section>

  <section className="audience-new wrap"><header><p className="kicker">Individualan pristup zdravlju · 18+</p><h2>Za koga su Natura Sanat savjetovanja?</h2><p><strong>Za sve punoljetne osobe</strong> koje žele unaprijediti prehranu, zdravlje i životne navike u skladu sa svojim potrebama, ciljevima i trenutačnim zdravstvenim stanjem.</p></header><div className="audience-cards">{audiences.map(item=><article key={item.title}><span aria-hidden>{item.icon}</span><h3>{item.title}</h3><p>{item.text}</p></article>)}</div><p className="audience-note"><strong>Svaka osoba ima svoj put.</strong> Savjetovanje prilagođavam vašim potrebama, ciljevima, životnim navikama i trenutačnom zdravstvenom stanju.</p></section>

  <section className="intro-service wrap"><div><span>Prvi korak za nove klijente</span><h2>Uvodna individualna procjena i savjetovanje</h2><p>Prije susreta pregledavam vaš zdravstveni upitnik, prehrambene i životne navike te ciljeve zbog kojih ste mi se obratili. Tijekom razgovora određujemo glavne prioritete i najbolji smjer daljnjeg rada.</p><p className="intro-highlight"><strong>Nakon savjetovanja dobivate personalizirani sažetak</strong> s glavnim prioritetima, prvim koracima i prijedlogom daljnjeg individualnog rada.</p></div><aside><strong>150 €</strong><span>60–90 min</span><a className="button" href="/savjetovanje">Saznajte više</a></aside></section>

  <section className="program-section" id="programi"><div className="wrap"><header><p className="kicker">Više individualne podrške</p><h2>Cjeloviti individualni programi</h2><p>Za one koji žele napraviti više za svoje zdravlje. Nakon uvodnog savjetovanja zajedno biramo daljnji rad koji najbolje odgovara potrebama i ciljevima.</p></header><div className="program-grid">{services.map(service=><article className={service.featured?"featured":""} key={service.slug}>{service.featured&&<span className="program-badge">Najopsežniji program</span>}<p className="program-eyebrow">{service.eyebrow}</p><h3>{service.title}</h3><strong>{service.duration}</strong><p>{service.lead}</p>{service.guide&&<small>Praktični vodič uključen u cijenu.</small>}<ArrowLink href={`/individualni-rad/${service.slug}`}>Otkrijte program</ArrowLink></article>)}</div><div className="center-actions"><ArrowLink href="/individualni-rad">Pogledajte sve usluge i cijene</ArrowLink></div></div></section>

  <section className="guides-feature"><div className="wrap guides-feature-grid"><div><p className="kicker">Znanje za svakodnevnu primjenu</p><h2>Vodiči i e-knjige</h2><p>Praktični digitalni vodiči nastali iz iskustva, edukacije i rada s klijentima. Donose recepte, ideje i jasne smjernice koje zdrave navike prenose u svakodnevni život.</p><ArrowLink href="/webshop">Pogledajte vodiče</ArrowLink></div><figure><Image src="/images/sandra/sandra-booklet-cover-v1.webp" alt="Boce prirodnih sokova uz mikrozelenje" fill sizes="(max-width: 900px) 100vw, 44vw"/></figure></div></section>

  <section className="about-band"><div className="wrap about-grid"><figure><Image src="/images/sandra/sandra-about-v1.webp" alt="Sandra Pavić Drašković" fill sizes="(max-width: 900px) 100vw, 36vw"/></figure><div><p className="kicker">O Sandri</p><h2>Stručno znanje. Osobno razumijevanje.</h2><p>Sandra je magistra farmacije, fitoaromaterapeutkinja i edukatorica. Kroz Natura Sanat pomaže ljudima jasnije razumjeti prehranu, dodatke i navike, uz poštovanje liječničkih preporuka i granica savjetovanja.</p><p>Njezine preporuke moraju imati mjesto u stvarnom danu. Zato razgovor ne počinje savršenim planom, nego osobom i onime što je u ovom trenutku moguće promijeniti.</p><ArrowLink href="/sandra">Pročitajte moju priču</ArrowLink></div></div></section>

  <section className="community-feature"><div className="wrap community-grid"><div><p className="kicker">Dio moje misije i doprinosa zajednici</p><h2>Podrška onkološkim bolesnicima kroz udruge i zajednicu</h2><p>Kao magistra farmacije, fitoaromaterapeutkinja i osoba s vlastitim iskustvom onkološke bolesti, dio znanja i iskustva rado vraćam zajednici kroz besplatna predavanja, radionice i edukativne aktivnosti.</p><p className="notice"><strong>Važno:</strong> podrška je edukativnog i savjetodavnog karaktera te se provodi komplementarno uz onkološko liječenje i preporuke nadležnog medicinskog tima.</p></div><figure><Image src="/images/sandra/sandra-speaking.jpg" alt="Sandra drži edukativno predavanje" fill sizes="(max-width: 900px) 100vw, 45vw"/></figure></div></section>

  <section className="testimonials"><div className="wrap"><header><p className="kicker">Što kažu klijenti</p><h2>Iskustva ljudi koji su učili i uvodili promjene uz Sandrinu podršku.</h2></header><div className="testimonial-grid">{featuredTestimonials.map(item=><figure className="testimonial-card" key={`${item.name}-${item.context}`}><blockquote>“{item.quote}”</blockquote><figcaption><strong>{item.name}</strong><span>{item.context}</span></figcaption></figure>)}</div><div className="testimonial-footer"><p className="testimonial-note">Izjave su jezično uređene i skraćene radi čitljivosti, bez mijenjanja smisla.</p><ArrowLink href="/iskustva">Pročitajte sva iskustva</ArrowLink></div></div></section>

  <section className="start-cta"><div className="wrap"><p className="kicker">Želite započeti?</p><h2>Prvi korak je uvodna individualna procjena i savjetovanje.</h2><p>Prije termina dobit ćete zdravstveni upitnik i suglasnost za suradnju kako bih se mogla kvalitetno pripremiti za naš razgovor.</p><strong>150 € · 60–90 min</strong><a className="button" href="/kontakt?tema=konzultacije&program=Uvodno%20savjetovanje">Pošaljite upit</a></div></section>
  </main><Footer/></>}
