import Image from "next/image";
import Link from "next/link";
import {ArrowLink,Footer,Header} from "./site-components";

const services=[
  {n:"01",title:"Individualne konzultacije",text:"90 minuta za jasan pregled prehrambenih navika, životnog stila, dodataka prehrani i svakodnevnih zdravstvenih odluka.",meta:"90 min · 200 €",href:"/savjetovanje"},
  {n:"02",title:"Predavanja i radionice",text:"Edukacije za tvrtke, udruge i organizacije, prilagođene publici i kontekstu događanja.",meta:"60 ili 90 min",href:"/predavanja"},
  {n:"03",title:"Digitalne knjižice",text:"Plaćeni edukativni materijali za samostalno čitanje i postupno uvođenje promjena.",meta:"U pripremi",href:"/knjizice"},
];

export default function Home(){return <><Header/><main>
<section className="hero"><div className="hero-copy"><p className="kicker">Farmaceutsko znanje za svakodnevne odluke</p><h1>Zdravlje treba razumjeti prije nego što ga počnemo mijenjati.</h1><p className="lede">Sandra Pavić Drašković povezuje farmaceutsko znanje, prehranu i zdravstvenu pismenost u jasne, praktične edukacije.</p><div className="actions"><Link className="button" href="/savjetovanje">Pošalji upit za konzultacije</Link><ArrowLink href="/sandra">Upoznaj Sandru</ArrowLink></div></div><figure className="hero-photo"><Image src="/images/sandra/sandra-hero.jpg" alt="Sandra Pavić Drašković u zelenom odijelu, naslonjena uz prozor" fill priority sizes="(max-width: 800px) 100vw, 48vw"/></figure></section>
<section className="statement"><div className="wrap"><p className="kicker">Bez brzih obećanja</p><h2>Jasno objašnjenje. Stvarni kontekst. Odluke koje se mogu provesti.</h2></div></section>
<section className="services wrap"><header><p className="kicker">Kako Sandra radi</p><h2>Tri načina za učenje i jasniji sljedeći korak.</h2></header><div className="service-list">{services.map(s=><article key={s.n}><span>{s.n}</span><div><h3>{s.title}</h3><p>{s.text}</p></div><strong>{s.meta}</strong><ArrowLink href={s.href}>Saznaj više</ArrowLink></article>)}</div></section>
<section className="split green"><figure><Image src="/images/sandra/sandra-speaking.jpg" alt="Sandra Pavić Drašković drži predavanje pred publikom" fill sizes="(max-width: 900px) 100vw, 50vw"/></figure><div><p className="kicker">Predavanja i radionice</p><h2>Stručne teme prevedene u razumljiv jezik.</h2><p>Predavanje traje 60 minuta. Predavanje s praktičnom radionicom traje 90 minuta, a praktični dio može uključivati izradu smoothija.</p><ArrowLink href="/predavanja">Pogledaj formate i cijene</ArrowLink></div></section>
<section className="about-band"><div className="wrap about-grid"><figure><Image src="/images/sandra/sandra-portrait-square.jpeg" alt="Portret Sandre Pavić Drašković" fill sizes="(max-width: 900px) 100vw, 36vw"/></figure><div><p className="kicker">Sandra</p><h2>Magistra farmacije, fitoaromaterapeutkinja i edukatorica.</h2><p>U radu spaja stručno znanje s razumijevanjem svakodnevnog života. Ne postavlja dijagnoze i ne mijenja liječničku terapiju.</p><ArrowLink href="/sandra">Više o Sandri</ArrowLink></div></div></section>
<section className="collab wrap"><div><p className="kicker">Edukacije i suradnje</p><h2>Znanje se širi kroz ljude i organizacije.</h2></div><div><p>Sandra surađuje s Institutom za gastroenterološke tumore, IGET, i Udrugom Budi dobro.</p><p className="fine">Točan oblik institucionalnih suradnji i dozvole za korištenje logotipa još se potvrđuju.</p></div></section>
<section className="newsletter"><div className="wrap newsletter-grid"><div><p className="kicker">Besplatni sadržaj</p><h2>PDF vodič i newsletter su u pripremi.</h2></div><div><p>Nećemo tražiti prijavu dok tema vodiča i pružatelj newslettera nisu potvrđeni.</p><span className="todo">TODO_CONFIRM_FREEBIE_TOPIC · TODO_SELECT_NEWSLETTER_PROVIDER</span></div></div></section>
</main><Footer/></>}
