import type {Metadata} from "next";
import Image from "next/image";

export const metadata:Metadata={
  title:"Nutrition consultation and education",
  description:"Individual nutrition consultations, lectures and educational guides by Sandra Drašković, Master of Pharmacy and phyto-aromatherapist.",
  alternates:{canonical:"/en",languages:{"hr-HR":"/","en":"/en"}},
};

const faqs = [
  ["Who is the individual consultation for?", "For people who want to understand nutrition, supplements and everyday habits in the context of their treatment, goals and real life."],
  ["What does the consultation involve?", "Sandra first reviews the agreed background information. The consultation then lasts at least 90 minutes, online or in Zagreb. You receive written educational guidance afterwards."],
  ["Can I send medical records through the first contact form?", "No. Your first enquiry should contain only your contact details and a short description of the topic. If any documents are relevant, you will receive separate instructions after the initial agreement."],
  ["Does the consultation replace medical care?", "No. Sandra does not diagnose conditions, prescribe treatment or change medication. The consultation helps you understand information and prepare better questions for your healthcare team."],
] as const;

function EnglishHeader(){return <header className="site-header"><div className="header-inner"><a className="brand header-brand" href="/en" aria-label="Sandra Drašković, English home page"><img className="header-logo" src="/sandra-draskovic-logo.png" alt="Sandra Drašković" width={738} height={346}/></a><nav aria-label="Main navigation"><a href="#about">About Sandra</a><a href="#consultation">Consultation</a><a href="#lectures">Lectures</a><a href="#guides">Guides</a><a href="#contact">Contact</a></nav><div className="languages" aria-label="Language selection"><a href="/" lang="hr">HR</a><span>/</span><a href="/en" lang="en" aria-current="page">EN</a></div><details className="mobile-menu"><summary>Menu</summary><div><a href="#about">About Sandra</a><a href="#consultation">Consultation</a><a href="#lectures">Lectures</a><a href="#guides">Guides</a><a href="#contact">Contact</a><a href="/">Hrvatski</a></div></details></div></header>}

function EnglishFooter({email}:{email:string}){return <footer><div className="wrap footer-grid"><div><a className="brand" href="/en">Sandra Drašković</a><p>Master of Pharmacy · phyto-aromatherapist · educator</p><p>Natura Sanat<br/>Nutrition and phyto-aromatherapy consultation.</p></div><div><strong>Work with Sandra</strong><a href="#consultation">Individual consultation</a><a href="#lectures">Lectures and workshops</a><a href="#guides">Educational guides</a></div><div><strong>Contact</strong><a href={`mailto:${email}`}>{email}</a><span>Online and in Zagreb</span></div><div><strong>Important</strong><p>Education and consultation do not replace medical examination, diagnosis or prescribed treatment.</p><a href="/">Hrvatska verzija</a></div></div><div className="wrap copyright">© {new Date().getFullYear()} Sandra Drašković <span>Natura Sanat</span></div></footer>}

export default function EnglishPage(){
  const email=process.env.NEXT_PUBLIC_CONTACT_EMAIL || "info@sandrapavicdraskovic.com";
  return <div lang="en"><EnglishHeader/><main>
    <section className="hero">
      <div className="hero-copy"><p className="kicker">Natura Sanat · individual consultation</p><h1>First, we understand the whole picture.</h1><p className="lede">For people who want to understand nutrition, supplements and everyday habits in the context of their treatment, goals and real life.</p><div className="hero-facts" aria-label="Key information"><span><strong>90+ min</strong> duration</span><span><strong>€200</strong> initial consultation</span><span><strong>Online / Zagreb</strong> format</span></div><div className="actions"><a className="button" href={`mailto:${email}?subject=Initial consultation enquiry`}>Request a consultation</a><a className="arrow-link" href="#process">How it works <span aria-hidden>→</span></a></div><p className="hero-note">All individual work begins with an initial consultation.</p></div>
      <figure className="hero-photo"><Image src="/images/sandra/sandra-hero.jpg" alt="Sandra Drašković sitting by a window" fill priority sizes="(max-width:800px) 100vw, 48vw"/></figure>
    </section>

    <section className="trust-strip" aria-label="Qualifications and key collaborations"><div className="wrap trust-strip-inner"><p><strong>Master of Pharmacy</strong><span>phyto-aromatherapist</span><span>educator</span></p><p><span>Collaborations</span><a href="https://budidobro.hr/" target="_blank" rel="noreferrer">Budi dobro</a><a href="https://iget.hr/" target="_blank" rel="noreferrer">IGET</a><a href="https://www.prezivjela.com/" target="_blank" rel="noreferrer">Preživjela. Što sada?</a></p></div></section>

    <section className="audience wrap" id="consultation"><div><p className="kicker">Who the consultation is for</p><h2>When general advice is no longer enough.</h2></div><div><p>One source tells you to remove a food. Another tells you to add a supplement. In between are your treatment, sleep, family, work, goals and the days when there is no room for a perfect plan.</p><p>Sandra does not begin with a ready-made meal plan. She first looks at what you already do, what you want to achieve, what you take and which changes are genuinely realistic in your daily life.</p><p className="notice">The consultation is educational. It does not diagnose conditions, change medical treatment or replace a medical examination.</p></div></section>

    <section className="process wrap" id="process"><header><p className="kicker">How Sandra works</p><h2>From your first enquiry to a clear recommendation.</h2></header><ol className="process-grid"><li><span>01</span><h3>Short enquiry</h3><p>Send only your contact details and the topic you would like to discuss. Do not send medical records at this stage.</p></li><li><span>02</span><h3>Agreement and consent</h3><p>If the service is suitable, you receive clear information about scope, privacy, payment and scheduling.</p></li><li><span>03</span><h3>Initial consultation</h3><p>At least 90 minutes, online or in Zagreb. Sandra reviews the agreed information before the appointment.</p></li><li><span>04</span><h3>Recommendation</h3><p>The process may end here, or Sandra may suggest an appropriate next step in a separate proposal.</p></li></ol></section>

    <section className="services"><header><p className="kicker">Services</p><h2>Different needs call for different kinds of support.</h2></header><div className="product-list"><article><div className="product-index"><span>01</span><small>First step for individual work</small></div><div><h3>Initial consultation</h3><p>A structured review of nutrition, supplements, habits and goals before deciding whether any further individual work is useful.</p><p className="product-detail">Online or in Zagreb</p></div><div className="product-action"><strong>90+ min · €200</strong><a className="arrow-link" href={`mailto:${email}?subject=Initial consultation enquiry`}>Send an enquiry <span aria-hidden>→</span></a></div></article><article id="lectures"><div className="product-index"><span>02</span><small>For companies, associations and communities</small></div><div><h3>Lectures and workshops</h3><p>Clear, practical education on nutrition, supplements and everyday habits, adapted to the audience and format.</p><p className="product-detail">Lecture, Q&amp;A and an optional practical section</p></div><div className="product-action"><strong>60 or 90 min</strong><a className="arrow-link" href={`mailto:${email}?subject=Lecture or workshop enquiry`}>Request a proposal <span aria-hidden>→</span></a></div></article><article id="guides"><div className="product-index"><span>03</span><small>Learn at your own pace</small></div><div><h3>Educational guides with recipes</h3><p>Digital materials that combine practical explanations with recipes for everyday meal planning and preparation.</p><p className="product-detail">Three Croatian-language digital editions are in preparation</p></div><div className="product-action"><strong>From €29</strong><a className="arrow-link" href="/webshop">View the guides <span aria-hidden>→</span></a></div></article></div></section>

    <section className="about-band" id="about"><div className="wrap about-grid"><figure><Image src="/images/sandra/sandra-about-v1.webp" alt="Sandra Drašković in a bright interior" fill sizes="(max-width:900px) 100vw, 36vw"/></figure><div><p className="kicker">About Sandra</p><h2>Professional knowledge. Personal understanding.</h2><p>Sandra is a Master of Pharmacy, phyto-aromatherapist and educator. Through Natura Sanat, she helps people understand nutrition, supplements and daily habits while respecting medical recommendations and the boundaries of consultation.</p><p>Her guidance has to fit into a real day. That is why the conversation begins with the person, their questions and what is realistically possible—not with a perfect plan.</p></div></div></section>

    <section className="faq wrap"><p className="kicker">Before you get in touch</p><h2>Useful questions to clarify from the start.</h2><div className="faq-list">{faqs.map(([question,answer])=><details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></section>

    <section className="final-cta" id="contact"><div className="wrap"><p className="kicker">First step</p><h2>All individual work begins with an initial consultation.</h2><p>Send a short enquiry without medical records. Sandra will confirm whether the service fits your needs and explain the next steps. Replies are normally sent within two business days.</p><div className="actions"><a className="button" href={`mailto:${email}?subject=Initial consultation enquiry`}>Email Sandra</a></div></div></section>
  </main><EnglishFooter email={email}/></div>;
}
