import type {Metadata} from "next";
import {LegalPage} from "../legal-page";
export const metadata:Metadata={title:"Prigovori, promjene termina i povrati",description:"Postupak pisanog prigovora, promjene termina i povrata za Natura Sanat usluge i digitalne vodiče.",alternates:{canonical:"/prigovori-i-povrati"}};
export default function Page(){return <LegalPage title="Prigovori, promjene termina i povrati" intro="Želimo da prije uplate znate što se događa ako se termin mora promijeniti, ako uslugu ne možete iskoristiti ili ako imate prigovor.">
<section><h2>Pisani prigovor</h2><p>Prigovor možete poslati putem <a href="/kontakt">kontaktnog obrasca</a> ili poštom na: Natura Sanat, Zelenjak 38, 10000 Zagreb. Navedite ime, kontakt, uslugu ili broj narudžbe i jasan opis problema. Nemojte slati nepotrebne zdravstvene podatke.</p><p>Potvrdit ćemo primitak i odgovoriti u zakonskom roku, trenutačno 15 dana od primitka. Slanje prigovora ne umanjuje druga prava potrošača.</p></section>
<section><h2>Ako klijent promijeni ili otkaže termin</h2><p>Najmanje 48 sati prije termina možete jednom odabrati novi raspoloživi termin ili zatražiti povrat iznosa plaćenog za neizvršenu uslugu. Kod otkazivanja manje od 48 sati prije termina ili nedolaska uplaćeni iznos se u pravilu ne vraća zbog rezerviranog vremena i pripreme. U opravdanim iznimnim okolnostima može se ponuditi novi termin.</p></section>
<section><h2>Ako Sandra promijeni ili otkaže termin</h2><p>Bit ćete obaviješteni što je prije moguće i dobiti novi termin bez dodatnog troška. Ako vam ponuđeni termin ne odgovara, vraća se puni iznos za neizvršenu uslugu. Kod programa se vraća razmjeran iznos za neodržane termine.</p></section>
<section><h2>Ako program nije iskorišten do kraja</h2><p>Veći programi mogu se plaćati po terminima, čime se smanjuje rizik plaćanja neiskorištenog dijela. Već pruženi termini, obavljena individualna priprema i isporučeni materijali ne refundiraju se, osim kada zakon propisuje drukčije. Za unaprijed plaćene, a neodržane termine primjenjuju se rokovi otkazivanja navedeni iznad.</p></section>
<section><h2>Digitalni vodič nije stigao ili ga nije moguće otvoriti</h2><p>Javite se putem kontaktnog obrasca i navedite broj narudžbe. Nakon provjere plaćanja može se izdati nova vremenski ograničena poveznica. Ako digitalni sadržaj nije isporučen ili nije usklađen s opisom, primjenjuju se odgovarajuća zakonska prava kupca.</p></section>
<section><h2>Zakonska prava</h2><p className="notice">Ova pravila ne ograničavaju pravo na jednostrani raskid ugovora sklopljenog na daljinu niti druga prava koja potrošaču pripadaju prema važećim propisima. Kada je za rani početak usluge ili trenutačnu isporuku digitalnog sadržaja potreban poseban pristanak, traži se zasebno i nije unaprijed označen.</p></section>
</LegalPage>}
