import type {Metadata} from "next";
import {controlService,services} from "../_data/services";
import {ArrowLink,Footer,Header} from "../site-components";

export const metadata:Metadata={title:"Individualna savjetovanja i programi",description:"Cijene, trajanje i sadržaj individualnih Natura Sanat savjetovanja i programa nakon uvodne procjene.",alternates:{canonical:"/individualni-rad"}};

export default function Page(){return <><Header/><main>
  <section className="page-hero green"><div><p className="kicker">Individualan pristup</p><h1>Kako vam mogu pomoći?</h1><p className="lede">Nakon uvodnog savjetovanja zajedno biramo daljnji rad koji najbolje odgovara vašim potrebama, ciljevima i životnoj situaciji.</p></div></section>
  <section className="service-catalog wrap" id="programi"><header><p className="kicker">Savjetovanja i programi</p><h2>Jasan opseg, cijena i način plaćanja prije početka.</h2><p>Za nove klijente prvi korak uvijek je <a href="/savjetovanje">uvodna individualna procjena i savjetovanje</a>. Program se ne odabire naslijepo, nego nakon upoznavanja vašeg konteksta.</p></header><div className="service-cards">{services.map(service=><article className={service.featured?"featured":""} key={service.slug}>{service.featured&&<span className="program-badge">Najopsežniji program</span>}<p className="program-eyebrow">{service.eyebrow}</p><h3>{service.title}</h3><div className="service-price"><strong>{service.price}</strong><span>{service.duration}</span></div><p>{service.lead}</p>{service.guide&&<small>Praktični vodič uključen u cijenu.</small>}<ArrowLink href={`/individualni-rad/${service.slug}`}>Saznajte više</ArrowLink></article>)}</div></section>
  <section className="control-card wrap"><div><p className="kicker">Za postojeće klijente</p><h2>{controlService.title}</h2><p>{controlService.description}</p><p className="fine">{controlService.condition}</p></div><aside><strong>{controlService.price}</strong><span>{controlService.duration}</span><p>{controlService.payment}</p><a className="button" href="/kontakt?tema=konzultacije&program=Kontrolna%20konzultacija">Dogovorite kontrolu</a></aside></section>
  <section className="payment-explainer"><div className="wrap"><p className="kicker">Plaćanje bez nejasnoća</p><h2>Termin se potvrđuje nakon uplate.</h2><div className="payment-grid"><article><span>Do 200 €</span><h3>Plaćanje u cijelosti</h3><p>Usluge do 200 € plaćaju se unaprijed, nakon što dogovorimo prikladnost usluge i termin.</p></article><article><span>Veći programi</span><h3>Moguće plaćanje u dijelovima</h3><p>Programi od 400 €, 600 € i 1.000 € mogu se platiti u jednakim obrocima od 200 €, prije svakog termina.</p></article><article><span>Važno</span><h3>Upit nije rezervacija</h3><p>Termin je potvrđen tek kada je evidentirana puna uplata ili prva dogovorena rata.</p></article></div></div></section>
  <section className="school-card wrap"><div><p className="kicker">Povremeni grupni program</p><h2>Škola detoxa</h2><p>Program se otvara u posebnim ciklusima. Cijena, termini, sadržaj i uključeni vodiči objavljuju se za svaki ciklus zasebno.</p></div><aside><strong>Prijave trenutačno nisu otvorene</strong><ArrowLink href="/kontakt?tema=programi&program=Škola%20detoxa">Pošaljite upit interesa</ArrowLink></aside></section>
  <section className="final-cta"><div className="wrap"><p className="kicker">Obvezan prvi korak</p><h2>Ne morate unaprijed znati koji vam program treba.</h2><p>Uvodna procjena traje 60–90 minuta i stoji 150 €. Nakon nje dobivate personalizirani sažetak i prijedlog smislenog nastavka.</p><div className="actions"><a className="button" href="/savjetovanje">Započnite ovdje</a></div></div></section>
  </main><Footer/></>}
