import type {Metadata} from "next";
import Image from "next/image";
import {ContentPage} from "../content-page";

export const metadata:Metadata={title:"Predavanja i radionice o prehrani",description:"Edukativna predavanja i praktične radionice Sandre Drašković za tvrtke, udruge, ljekarne i zajednice, online ili uživo.",alternates:{canonical:"/predavanja"}};
const faq=[["Treba li sudionicima medicinska dokumentacija?","Ne. Za grupna predavanja i radionice ne prikuplja se medicinska dokumentacija sudionika."],["Jesu li radionice medicinska usluga?","Ne. Sadržaj je edukativan i ne uključuje dijagnozu, liječenje ni promjenu propisane terapije."],["Mogu li se predavanje i tema prilagoditi organizaciji?","Da. Publika, cilj, trajanje, prostor, oprema, alergeni i ukupan trošak dogovaraju se u ponudi prije rezervacije."]] as const;
export default function Page(){const faqSchema={"@context":"https://schema.org","@type":"FAQPage",mainEntity:faq.map(([name,text])=>({"@type":"Question",name,acceptedAnswer:{"@type":"Answer",text}}))};return <ContentPage eyebrow="Predavanja i radionice" title="Znanje koje publika može primijeniti." intro="Edukativna predavanja i praktične radionice za tvrtke, udruge, ljekarne i zajednice, online ili uživo, bez obećanja brzih zdravstvenih rješenja.">
<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqSchema)}}/>
<h2>Tema prema potrebama publike</h2><p>Prije dogovora zanima me kome se obraćam i s kakvim pitanjima ljudi dolaze. Predavanje za zaposlenike koji jedu usput neće izgledati isto kao radionica za članove udruge.</p>
<ul><li>Cjelovita biljna prehrana: sastavljanje obroka i svakodnevna priprema.</li><li>Sokovi, smoothieji i doručak: recepti, sastojci i razlika između napitka i obroka.</li><li>Dodaci prehrani: čitanje deklaracije i pitanja za liječnika ili ljekarnika.</li><li>Prehrambene navike tijekom oporavka: edukacija uz poštovanje preporuka zdravstvenog tima.</li></ul>
<h2>Odaberi format</h2><h3>Predavanje, 60 minuta</h3><p>Dogovorena tema i prostor za pitanja publike.</p><h3>Predavanje s radionicom, 90 minuta</h3><p>Predavanje, pitanja i praktičan dio. Prostor, opremu, sastojke i alergene dogovaramo unaprijed.</p><h3>Snimke ranijih radionica</h3><p>Na starom webu bilo je pet edukativnih snimki. Trenutačno nisu u prodaji; sačuvane su kao arhiva tema do stručne i pravne provjere.</p><p><a className="arrow-link" href="/snimke-radionica">Pregledaj arhivu snimki →</a></p>
<h2>Besplatne radionice i suradnje</h2><p>Sandra je održavala i besplatne edukativne radionice za onkološke pacijente u suradnji s udrugama Budi dobro i IGET. Takve suradnje predstavljaju se kao edukacija i podrška zajednici, bez obećanja ishoda i bez zamjene za medicinsku skrb.</p>
<h2>Treba li medicinska dokumentacija?</h2><p><strong>Ne.</strong> Za grupno predavanje, radionicu ili edukativnu snimku ne šalju se nalazi, dijagnoze ni popis terapije. Ako osoba želi razgovarati o vlastitoj situaciji, upućuje se na zdravstveni tim ili na odvojeni postupak uvodnog savjetovanja. Dokumentacija se tada traži samo ako je potrebna, nakon obavijesti o obradi i odgovarajuće privole.</p><p><a className="arrow-link" href="/dokumenti">Provjeri pravila za dokumentaciju →</a></p>
<h2>Suradnja s ljekarnama i zdravstvenim stručnjacima</h2><p>Otvorena sam za zajedničke edukacije i sadržaje. Uloge, stručnu provjeru i eventualnu promociju proizvoda dogovaramo prije suradnje. Poznanstvo s liječnikom ili ljekarnom ne prikazujem kao njihovu preporuku moje usluge.</p>
<figure className="portrait-inline landscape"><Image src="/images/sandra/sandra-speaking.jpg" alt="Sandra tijekom predavanja" width={1600} height={1200} sizes="(max-width:900px) 100vw, 55vw"/></figure><h2>Ponuda prije rezervacije</h2><p>Cijena ovisi o temi, formatu, lokaciji i pripremi. Nakon kratkog upita dobivaš ponudu s ukupnom cijenom, opsegom usluge i uvjetima rezervacije.</p><a className="button" href="/kontakt?tema=predavanje">Zatraži ponudu za predavanje</a>
<h2>Česta pitanja</h2><div className="faq-list compact">{faq.map(([question,answer])=><details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div>
<p className="fine">Predavanja su edukativna. Ne uključuju dijagnostiku ni individualno liječenje, a pitanja o terapiji upućujemo nadležnom zdravstvenom stručnjaku.</p></ContentPage>}
